# MouseHumanMatches.R ---------------------------------------------------------
#
#
#
# Antoine Beauchamp
# Created: August 4th, 2021
# Edited: March 14th, 2022

# Mouse labels 67 / Human labels 88 -------------------------------------------

dfMouseHumanMatches_H88M67 <- tibble::tibble(Mouse = c("Claustrum", 
                                                       "Piriform area",
                                                       "Subiculum",
                                                       "Field CA1", 
                                                       "Field CA2",
                                                       "Field CA3",
                                                       "Dentate gyrus",
                                                       "Anterior cingulate area",
                                                       "Primary auditory area",
                                                       "Primary motor area",
                                                       "Primary somatosensory area",
                                                       "Visual areas",
                                                       "Pallidum",
                                                       "Striatum ventral region",
                                                       "Caudoputamen",
                                                       "Cortical subplate-other",
                                                       "Inferior colliculus",
                                                       "Superior colliculus, sensory related",
                                                       "Medulla",
                                                       "Pons",
                                                       "Hypothalamus",
                                                       "Thalamus",
                                                       "Lingula (I)",
                                                       "Declive (VI)",
                                                       "Folium-tuber vermis (VII)",
                                                       "Pyramus (VIII)",
                                                       "Uvula (IX)", 
                                                       "Nodulus (X)", 
                                                       "Simple lobule",
                                                       "Crus 1",
                                                       "Crus 2",
                                                       "Paramedian lobule",
                                                       "Copula pyramidis",
                                                       "Flocculus",
                                                       "Paraflocculus",
                                                       "Cerebellar nuclei"),
                                             Human = c("claustrum",
                                                       "piriform cortex",
                                                       "subiculum",
                                                       "CA1 field",
                                                       "CA2 field",
                                                       "CA3 field",
                                                       "dentate gyrus",
                                                       "cingulate gyrus",
                                                       "Heschl's gyrus", 
                                                       "precentral gyrus", 
                                                       "postcentral gyrus",
                                                       "cuneus",
                                                       "globus pallidus",
                                                       "nucleus accumbens",
                                                       "caudate nucleus",
                                                       "amygdala",
                                                       "inferior colliculus",
                                                       "superior colliculus",
                                                       "myelencephalon",
                                                       "pons",
                                                       "hypothalamus",
                                                       "thalamus",
                                                       "vermal I-II",
                                                       "vermal VI", 
                                                       "vermal VIIAf",
                                                       "vermal VIIIA", 
                                                       "vermal IX", 
                                                       "vermal X",
                                                       "VI",
                                                       "crus I",
                                                       "crus II",
                                                       "VIIB",
                                                       "VIIIA", 
                                                       "X",
                                                       "IX",
                                                       "cerebellar nuclei"))


fileout <- "data/MouseHumanMatches_H88M67.csv"
readr::write_csv(x = dfMouseHumanMatches_H88M67, 
                 file = fileout)

