#!/bin/bash -l

source activate_venv

outdir=data/MLP_outcomes/

if [ ! -d "$outdir" ]; then
	mkdir "$outdir"
fi


for i in {1..500}
do
 echo "Iteration $i"

 python3 train_multilayer_perceptron.py \
	 --datadir data/ \
	 --outdir $outdir \
	 --labels region67 \
	 --mousedata region67 \
	 --humandata region88 \
	 --nunits 200 \
	 --L2 1e-6 \
	 --nepochs 200 \
	 --learningrate 1e-5 \
	 --confusionmatrix true \
	 --voxeltransform true

 mv ${outdir}MLP_ConfusionMatrix_Training_Region67_Layers3_Units200_L21e-06.csv \
	 ${outdir}MLP_ConfusionMatrix_Training_Region67_Layers3_Units200_L21e-06_$i.csv

 mv ${outdir}MLP_Region67_Layers3_Units200_L21e-06_HumanProb_Region88.csv \
	 ${outdir}MLP_Region67_Layers3_Units200_L21e-06_HumanProb_Region88_$i.csv

 mv ${outdir}MLP_Region67_Layers3_Units200_L21e-06_HumanTx_Region88.csv \
	 ${outdir}MLP_Region67_Layers3_Units200_L21e-06_HumanTx_Region88_$i.csv

 mv ${outdir}MLP_Region67_Layers3_Units200_L21e-06_MouseProb_Region67.csv \
	 ${outdir}MLP_Region67_Layers3_Units200_L21e-06_MouseProb_Region67_$i.csv

 mv ${outdir}MLP_Region67_Layers3_Units200_L21e-06_MouseTx_Region67.csv \
	 ${outdir}MLP_Region67_Layers3_Units200_L21e-06_MouseTx_Region67_$i.csv

mv ${outdir}MLP_Region67_Layers3_Units200_L21e-06_MouseVoxelTx.csv \
	${outdir}MLP_Region67_Layers3_Units200_L21e-06_MouseVoxelTx_$i.csv

mv ${outdir}MLP_Region67_Layers3_Units200_L21e-06_HumanVoxelTx.csv \
	${outdir}MLP_Region67_Layers3_Units200_L21e-06_HumanVoxelTx_$i.csv

done

deactivate
