#!/bin/bash

# ----------------------------------------------------------------------------
# process_expression_data
# Author: Antoine Beauchamp
#
# Pipeline to process mouse and human gene expression data sets.
#
# Pipeline steps:
# 1. Create a set of atlas labels at multiple levels of granularity using
#    the neuroanatomical trees.
# 2. Create a CSV file containing mouse-human canonical neuroanatomical pairs.
# 3. Intersect mouse and human gene sets with mouse-human gene homologs
#    (in label_expression_matrices.R)
# 4. Label mouse voxel-wise and human sample-wise expression matrices with 
#    neuroanatomical labels at multiple levels in the hierarchy.
# 5. Normalize mouse voxel-wise expression matrix.
# 6. Normalize human sample-wise expression matrix.
# 7. Normalize and aggregate mouse expression matrix under 67 atlas labels.
# 8. Normalize and aggregate human expression matrix under 88 atlas labels.

#Create atlas labels
echo "Creating pruned atlas labels from neuroanatomical trees..."
Rscript create_tree_labels.R \
	--outdir data/ \
	--mousetree AMBA/data/MouseExpressionTree_DSURQE.RData \
	--humantree AHBA/data/HumanExpressionTree.RData

#Define canonical neuroanatomical pairs
echo "Define canonical neuroanatomical pairs..."
Rscript create_neuro_pairs.R \
	--outdir data/ \
	--outfile MouseHumanMatches_H88M67.csv

#Label expression matrices
echo "Labelling mouse and human expression matrices..."
Rscript label_expression_matrices.R \
	--mousematrix AMBA/data/MouseExpressionMatrix_voxel_coronal_maskcoronal_log2_grouped_imputed.csv \
	--humanmatrix AHBA/data/HumanExpressionMatrix_samples_pipeline_abagen.csv \
	--mousetree AMBA/data/MouseExpressionTree_DSURQE.RData \
	--humantree AHBA/data/HumanExpressionTree.RData \
	--homologs data/MouseHumanGeneHomologs.csv \
	--outdir data/ \
	--savemouse true \
	--savehuman true

#Normalize and aggregate labelled expression matrices
echo "Processing labelled expression matrices..."

echo "Normalizing mouse voxel expression matrix..."
Rscript process_labelled_matrix.R \
	--infile data/MouseExpressionMatrix_voxel_coronal_maskcoronal_log2_grouped_imputed_labelled.csv \
	--scale true \
	--aggregate false \
	--outdir data/ \
	--verbose true

echo "Normalizing human sample expression matrix..."
Rscript process_labelled_matrix.R \
	--infile data/HumanExpressionMatrix_samples_pipeline_abagen_labelled.csv \
	--scale true \
	--aggregate false \
	--outdir data/ \
	--verbose true

echo "Normalizing and aggregating mouse voxel expression matrix..."
Rscript process_labelled_matrix.R \
	--infile data/MouseExpressionMatrix_voxel_coronal_maskcoronal_log2_grouped_imputed_labelled.csv \
	--scale true \
	--aggregate true \
	--nlabels 67 \
	--outdir data/ \
	--verbose true

echo "Normalizing and aggregating human sample expression matrix..."
Rscript process_labelled_matrix.R \
	--infile data/HumanExpressionMatrix_samples_pipeline_abagen_labelled.csv \
	--scale true \
	--aggregate true \
	--nlabels 88 \
	--outdir data/ \
	--verbose true

#Create a mouse voxel-wise expression matrix with only isocortical labels
Rscript subset_labels.R

#Copy aggregated expression matrices into isocortical data dir
cp data/MouseExpressionMatrix_ROI_Region67_scaled.csv data/isocortex/
cp data/HumanExpressionMatrix_ROI_Region88_scaled.csv data/isocortex/

# Normalize and aggregate isocortical data

echo "Normalizing mouse isocortical expression matrix..."
Rscript process_labelled_matrix.R \
	--infile data/isocortex_scaled/MouseExpressionMatrix_voxel_coronal_maskcoronal_log2_grouped_imputed_labelled.csv \
	--scale true \
	--aggregate false \
	--outdir data/isocortex_scaled/ \
	--verbose true

echo "Normalizing human isocortical expression matrix..."
Rscript process_labelled_matrix.R \
	--infile data/isocortex_scaled/HumanExpressionMatrix_samples_pipeline_abagen_labelled.csv \
	--scale true \
	--aggregate false \
	--outdir data/isocortex_scaled/ \
	--verbose true

echo "Normalizing and aggregating mouse isocortical expression matrix..."
Rscript process_labelled_matrix.R \
	--infile data/isocortex_scaled/MouseExpressionMatrix_voxel_coronal_maskcoronal_log2_grouped_imputed_labelled.csv \
	--scale true \
	--aggregate true \
	--nlabels 67 \
	--outdir data/isocortex_scaled/ \
	--verbose true

echo "Normalizing and aggregating human isocortical expression matrix..."
Rscript process_labelled_matrix.R \
	--infile data/isocortex_scaled/HumanExpressionMatrix_samples_pipeline_abagen_labelled.csv \
	--scale true \
	--aggregate true \
	--nlabels 88 \
	--outdir data/isocortex_scaled/ \
	--verbose true


