---
title: "Mouse Human Mapping Paper 1"
subtitle: "Results 1"
author: "Antoine Beauchamp"
date: 'November 3rd, 2021'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      include = FALSE,
                      cache.lazy = FALSE)
```

```{r libraries}
#Libraries
suppressPackageStartupMessages(library(tidyverse))
library(grid)
library(gridExtra)
library(pheatmap)
library(ggplotify)
library(ggnewscale)
library(RMINC)
library(MRIcrotome)
library(data.tree)
library(RColorBrewer)
```

```{r functions}
#Functions
source("/projects/abeauchamp/Functions/TreeTools.R")
source("/projects/abeauchamp/Functions/mincBuildArray.R")
source("/projects/abeauchamp/Projects/MouseHumanMapping/Functions/ProcessingTools.R")
source("/projects/abeauchamp/Projects/MouseHumanMapping/Functions/buildSimilarityMatrix.R")
```

```{r import}
#Set path
pathHome <- "/projects/abeauchamp/Projects/MouseHumanMapping/Paper_Descriptive/"

#Import data
dfExprMouse <- suppressMessages(read_csv(str_c(pathHome, "Data/", "MouseExpressionMatrix_Voxel_coronal_maskcoronal_imputed_labelled.csv")))
dfExprHuman <- suppressMessages(read_csv(str_c(pathHome, "Data/", "HumanExpressionMatrix_Samples_labelled.csv")))

#Load mouse/human labels (Objects: listLabelsMouseReordered, listLabelsHumanReordered)
load(str_c(pathHome, "Data/", "TreeLabelsReordered.RData"))

#Import MICe data tree
load(str_c("/projects/abeauchamp/Projects/MouseHumanMapping/AllenMouseBrainAtlas/Data/MouseExpressionTree_DSURQE.RData"))
treeMouse <- Clone(treeMouseExpr)
rm(treeMouseExpr)

#Remove white matter and ventricles
pruneAnatTree(treeMouse, 
              nodes = c("fiber tracts", "ventricular systems"),
              method = "AtNode")

#Import AHBA data tree
load("/projects/abeauchamp/Projects/MouseHumanMapping/AllenHumanBrainAtlas/Data/HumanExpressionTree_Samples.RData")
treeHuman <- Clone(treeHumanExpr)
rm(treeHumanExpr)

#Fix human colour names (need to start with #)
treeHuman$Do(function(node){
  node$color_hex_triplet <- str_c("#", node$color_hex_triplet)
})

#Remove white matter and ventricles
pruneAnatTree(treeHuman,
              nodes = c("white matter", "sulci & spaces"),
              method = "AtNode")

#Import DSURQE labels and template
dsurqeLabels <- mincGetVolume("/projects/abeauchamp/Atlases/DSURQE/DSURQE_40micron_labels.mnc")
dsurqeAnat <- mincGetVolume("/projects/abeauchamp/Atlases/DSURQE/DSURQE_40micron_average.mnc")
dsurqeMask <- mincGetVolume("/projects/abeauchamp/Atlases/DSURQE/DSURQE_40micron_mask.mnc")
```

```{r normalization}
#Extract labels from data frames
dfLabelsMouse <- dfExprMouse %>% select(contains("Region"))
dfLabelsHuman <- dfExprHuman %>% select(contains("Region"))

#Normalize mouse data
dfExprMouse_scaled <- dfExprMouse %>% 
  select(-contains("Region")) %>% 
  as.matrix() %>% 
  scaler(axis = "rows") %>% 
  scaler(scale = FALSE, axis = "columns") %>% 
  as_tibble() %>% 
  bind_cols(dfLabelsMouse)

#Normalize human data
dfExprHuman_scaled <- dfExprHuman %>% 
  select(-contains("Region")) %>% 
  as.matrix() %>% 
  scaler(axis = "rows") %>% 
  scaler(scale = FALSE, axis = "columns") %>% 
  as_tibble() %>% 
  bind_cols(dfLabelsHuman)

#Extract genes list from mouse data (same as human)
genes <- colnames(dfExprMouse_scaled)[!str_detect(colnames(dfExprMouse_scaled), "Region")]

rm(dfExprMouse, dfExprHuman)
```

```{r}
treeMouse_11 <- Clone(treeMouse)
pruneAnatTree(treeMouse_11,
              nodes = listLabelsMouseReordered$Region11_reordered,
              method = "BelowNode")
atlasMouse_11 <- hanatToAtlas(treeMouse_11, mincArray(dsurqeLabels))
dfAtlasMouse_11 <- hanatToAtlasDefs(treeMouse_11)

dsurqeAnat_3d <- mincArray(dsurqeAnat)
dsurqeMask_3d <- mincArray(dsurqeMask)

dsurqeAnat_3d[dsurqeMask_3d == 0] <- NA

anatLow <-  700
anatHigh <- 1400
dsurqeAnat_3d[dsurqeAnat_3d >= anatHigh] <- anatHigh
dsurqeAnat_3d[dsurqeAnat_3d <= anatLow] <- anatLow
dims <- dim(dsurqeAnat_3d)

slice <- 100
sliceSelectionAnat <- dsurqeAnat_3d[1:dims[1], 1:dims[2], slice]
colnames(sliceSelectionAnat) <- 1:ncol(sliceSelectionAnat)
rownames(sliceSelectionAnat) <- nrow(sliceSelectionAnat):1

dfSliceSelectionAnat <- sliceSelectionAnat %>% 
  as_tibble(rownames = "x") %>% 
  pivot_longer(-x, names_to = "y", values_to = "Intensity") %>% 
  mutate_all(.funs = as.numeric)

atlasMouse_11_3d <- mincArray(atlasMouse_11)
atlasMouse_11_3d[dsurqeMask_3d == 0] <- NA
atlasMouse_11_3d[atlasMouse_11_3d == 0] <- NA
sliceSelectionLabels <- atlasMouse_11_3d[1:dims[1], 1:dims[2], slice]
colnames(sliceSelectionLabels) <- 1:ncol(sliceSelectionLabels)
rownames(sliceSelectionLabels) <- nrow(sliceSelectionLabels):1

dfSliceSelectionLabels <- sliceSelectionLabels %>% 
  as_tibble(rownames = "x") %>% 
  pivot_longer(-x, names_to = "y", values_to = "Label") %>% 
  mutate_all(.funs = as.numeric) 

dfSliceSelection <- inner_join(dfSliceSelectionAnat,
                               dfSliceSelectionLabels,
                               by = c("x", "y"))

dfMouseColours <- treeMouse_11$Get("color_hex_triplet", filterFun = isLeaf) %>%
  enframe(name = "Structure",
          value = "Colour") %>% 
  inner_join(dfAtlasMouse_11,
             by = "Structure") %>% 
  semi_join(dfSliceSelection,
            by = "Label") %>% 
  arrange(Label)

dfSliceSelection <- dfSliceSelection %>% 
  filter(y <= 400) %>% 
  mutate(Label = factor(Label))

asp <- max(dfSliceSelection$x)/max(dfSliceSelection$y)

sliceAMBALegend <- ggplot(dfSliceSelection, aes(x = x, y = y)) + 
  geom_tile(aes(fill = Intensity),
            alpha = 0.5) + 
  scale_fill_gradient(low = gray.colors(255)[1],
                      high = gray.colors(255)[255],
                      na.value = 'transparent',
                      guide = F) + 
  new_scale_fill() + 
  geom_tile(aes(fill = Label)) + 
  scale_fill_manual(na.value = 'transparent',
                      values = dfMouseColours$Colour,
                    guide = F) +
  coord_fixed() +
  theme_void() +
  # theme_minimal() +
  theme(plot.margin = margin(t = 0, r = 0, b = 0, l = 0))
sliceAMBALegend_grob <- ggplotGrob(sliceAMBALegend) %>% grid.force()
sliceAMBALegend_panel_grob <- getGrob(sliceAMBALegend_grob, "panel.7-5-7-5")

rm(treeMouse_11,
   atlasMouse_11,
   dfAtlasMouse_11,
   dsurqeAnat_3d,
   dsurqeMask_3d,
   slice,
   sliceSelectionAnat,
   atlasMouse_11_3d,
   sliceSelectionLabels,
   dfSliceSelectionAnat,
   dfSliceSelectionLabels,
   dfSliceSelection,
   dfMouseColours)
```

```{r results1-fig1-panelA-heatmap}
# Figure 1: Heatmap processing ------------------------------------------------

#Compute average gene expression for 67 mouse brain regions
matExprMouse_scaled <- dfExprMouse_scaled %>% 
  select(Region = Region67,
         genes) %>% 
  group_by(Region) %>% 
  summarise_all(mean) %>% 
  ungroup() %>% 
  column_to_rownames("Region") %>% 
  as.matrix() %>% 
  t()

#Compute average gene expression for 88 human brain regions
matExprHuman_scaled <- dfExprHuman_scaled %>% 
  select(Region = Region88,
         genes) %>% 
  group_by(Region) %>% 
  summarise_all(mean) %>% 
  ungroup() %>% 
  column_to_rownames("Region") %>% 
  as.matrix() %>% 
  t()

#Compute human-mouse similarity matrix in gene space
matSim_H88M67_AllGenes <- buildSimilarityMatrix(x1 = matExprHuman_scaled, 
                                                x2 = matExprMouse_scaled)

#Order similarity matrix rows/columns according to brain organization
matSim_H88M67_AllGenes <- matSim_H88M67_AllGenes[,match(listLabelsMouseReordered$Region67_reordered, colnames(matSim_H88M67_AllGenes))]
matSim_H88M67_AllGenes <- matSim_H88M67_AllGenes[match(listLabelsHumanReordered$Region88_reordered, rownames(matSim_H88M67_AllGenes)),]

#Create annotation data frame for mouse regions
#Annotations use 11 coarser brain ROIs
dfAnnotationMouse <- dfLabelsMouse %>% 
  select(Region67, Region11) %>% 
  distinct() %>% 
  column_to_rownames("Region67") %>% 
  rename(MouseRegion = Region11)

#Order mouse annotations according to brain organization
indOrderMouse <- match(listLabelsMouseReordered$Region67_reordered, rownames(dfAnnotationMouse))
dfAnnotationMouse$MouseRegion <- dfAnnotationMouse$MouseRegion[indOrderMouse]
rownames(dfAnnotationMouse) <- rownames(dfAnnotationMouse)[indOrderMouse]

dfAnnotationMouse$MouseRegion <- factor(dfAnnotationMouse$MouseRegion, levels = listLabelsMouseReordered$Region11_reordered)

#Repeat for human regions
dfAnnotationHuman <- dfLabelsHuman %>% 
  select(Region88, Region16) %>% 
  distinct() %>% 
  column_to_rownames("Region88") %>% 
  rename(HumanRegion = Region16)

indOrderHuman <- match(listLabelsHumanReordered$Region88_reordered, rownames(dfAnnotationHuman))
dfAnnotationHuman$HumanRegion <- dfAnnotationHuman$HumanRegion[indOrderHuman]
rownames(dfAnnotationHuman) <- rownames(dfAnnotationHuman)[indOrderHuman]

dfAnnotationHuman$HumanRegion <- factor(dfAnnotationHuman$HumanRegion, levels = listLabelsHumanReordered$Region16_reordered)

#Prune mouse tree to 11 regions for cluster annotations
treeMouse_11 <- Clone(treeMouse)
pruneAnatTree(treeMouse_11,
              nodes = listLabelsMouseReordered$Region11,
              method = "BelowNode")

#Prune human tree to 16 regions for cluster annotations
treeHuman_16 <- Clone(treeHuman) 
pruneAnatTree(treeHuman_16,
              nodes = listLabelsHumanReordered$Region16,
              method = "BelowNode")

#Get colour annotation from trees
coloursMouse <-  treeMouse_11$Get("color_hex_triplet", filterFun = isLeaf)
indOrderMouseColours <- match(listLabelsMouseReordered$Region11_reordered, names(coloursMouse))
coloursMouse <- coloursMouse[indOrderMouseColours]

coloursHuman <- treeHuman_16$Get("color_hex_triplet", filterFun = isLeaf)
indOrderHumanColours <- match(listLabelsHumanReordered$Region16_reordered, names(coloursHuman))
coloursHuman <- coloursHuman[indOrderHumanColours]

annotation_colours <- list(MouseRegion = coloursMouse,
                           HumanRegion = coloursHuman)

#Create a set of modified colours for clearer visualization. 
#To be used for text colouring mostly
annotation_colours_mod <- annotation_colours
annotation_colours_mod$MouseRegion["Isocortex"] <- "#68EC68"
annotation_colours_mod$MouseRegion["Cerebellar cortex"] <- "#E6E67B"
annotation_colours_mod$MouseRegion["Cerebellar nuclei"] <- "#E6E67B"

annotation_colours_mod$HumanRegion["insula"] <- "#E6E658"
annotation_colours_mod$HumanRegion["diencephalon"] <- "#85DD63"
annotation_colours_mod$HumanRegion["pons"] <- "#00E0A4"


# Figure 1: Heatmap base ggplot -----------------------------------------------

heatmapColours <- colorRampPalette(rev(brewer.pal(n = 9, name = "RdBu")))(100)

#Generate similarity matrix heatmap and convert to ggplot object
fig1_heatmap_ggplot <- pheatmap(matSim_H88M67_AllGenes,
                                color = heatmapColours,
                                cluster_cols = F, cluster_rows = F,
                                # border_color = "grey80",
                                border_color = NA,
                                show_rownames = F, show_colnames = F,
                                annotation_row = dfAnnotationHuman,
                                annotation_col = dfAnnotationMouse,
                                annotation_colors = annotation_colours,
                                legend = T,
                                annotation_legend = F,
                                annotation_names_col = F, annotation_names_row = F) %>% 
  as.ggplot()


# Figure 1: Heatmap matrix ----------------------------------------------------

#Convert the pheatmap plot to grob and force the gTree
fig1_heatmap_main_grob <- ggplotGrob(fig1_heatmap_ggplot) %>% grid.force()

#Extract the matrix grob from the plot
fig1_heatmap_main_matrix_grob <- fig1_heatmap_main_grob %>% 
  getGrob("matrix.4-3-4-3") 

#Extract the row annotations and reposition them
fig1_heatmap_main_rowannotations_grob <- fig1_heatmap_main_grob %>% 
  getGrob("row_annotation.4-2-4-2") %>%
  editGrob(x = unit(0,'npc'),
           width = unit(0.9, 'npc'),
           just = "left")

#Exract the column annotations and reposition them
fig1_heatmap_main_colannotations_grob <- fig1_heatmap_main_grob %>% 
  getGrob("col_annotation.3-3-3-3") %>% 
  editGrob(y = unit(0.1, 'npc'),
           height = unit(0.9, 'npc'),
           just = "bottom")

#Extract the legend 
fig1_heatmap_main_legend_grob <- fig1_heatmap_main_grob %>% 
  getGrob("legend.4-5-5-5")

#Recombine the plot into a single grob layout
#Annotation sizes are fixed in inches. Matrix fills the remaining space
fig1_heatmap_main_grob <- arrangeGrob(fig1_heatmap_main_colannotations_grob,
                                      fig1_heatmap_main_rowannotations_grob,
                                      fig1_heatmap_main_matrix_grob,
                                      layout_matrix = rbind(c(NA, 1),
                                                            c( 2, 3)),
                                      widths = unit(c(0.1, 0.9), c('inch', 'null')),
                                      heights = unit(c(0.1, 0.9), c('inch', 'null')))



# Figure 1: Heatmap legend ----------------------------------------------------

fig1_heatmap_legend_title <- textGrob("Correlation",
                                      x = unit(0.5, 'inch'),
                                      y = 0.8,
                                      rot = 90)
fig1_heatmap_legend_grob <- gTree(children = gList(fig1_heatmap_main_legend_grob,
                                                   fig1_heatmap_legend_title))



# Figure 1: Heatmap mouse labels ----------------------------------------------

#1. Mouse label text
#The mouse labels are acronyms for 11 coarse regions
fig1_heatmap_labsmouse_text <- treeMouse_11$Get("acronym", filterFun = isLeaf) %>% 
  enframe(name = "Region",
          value = "Acronym") %>% 
  mutate(Region = factor(Region, levels = listLabelsMouseReordered$Region11_reordered)) %>% 
  arrange(Region) %>% 
  pull(Acronym) %>% 
  as.character()

#Mouse label x positions
fig1_heatmap_labsmouse_text_x <- c(0.305, #Cortical subplate
                                   0.533, #Olfactory areas
                                   0.952, #Hippocampal formation
                                   1.637, #Isocortex
                                   2.284, #Cerebral nuclei
                                   2.474, #Interbrain
                                   2.665, #Midbrain
                                   2.855, #Pons
                                   3.045, #Medulla
                                   3.312, #Cerebellar cortex
                                   3.655) #Cerebellar nuclei

#Mouse label y positions are organized in two rows
fig1_heatmap_labsmouse_text_y <- rep(c(0.3,0.125), length.out = length(fig1_heatmap_labsmouse_text))

#Colours for the mouse labels
fig1_heatmap_labsmouse_text_col <- annotation_colours_mod$MouseRegion

#Create the text grob for the mouse labels
fig1_heatmap_labsmouse_text_grob <- textGrob(fig1_heatmap_labsmouse_text,
                                             x = unit(fig1_heatmap_labsmouse_text_x, 'inch'),
                                             y = unit(fig1_heatmap_labsmouse_text_y, 'inch'),
                                             just = "centre",
                                             gp = gpar(fontsize = 10, 
                                                       col = fig1_heatmap_labsmouse_text_col,
                                                       fontface = "bold"))

#2. Mouse label lines
#Positions of the lines are dependent on text positions
fig1_heatmap_labsmouse_line_x0 <- fig1_heatmap_labsmouse_text_x + c(-0.1, #Cortical subplate
                                                                    NA, #Olfactory areas
                                                                    0, #Hippocampal formation
                                                                    NA, #Isocortex
                                                                    0, #Cerebral nuclei
                                                                    NA, #Interbrain
                                                                    0, #Midbrain
                                                                    NA, #Pons
                                                                    -0.148, #Medulla
                                                                    NA, #Cerebellar cortex
                                                                    0.13) #Cerebellar nuclei
fig1_heatmap_labsmouse_line_x1 <- fig1_heatmap_labsmouse_line_x0 + c(0, #Cortical subplate
                                                                     0, #Olfactory areas
                                                                     0, #Hippocampal formation
                                                                     0, #Isocortex
                                                                     0, #Cerebral nuclei
                                                                     0, #Interbrain
                                                                     0, #Midbrain
                                                                     0, #Pons
                                                                     0.148, #Medulla
                                                                     0, #Cerebellar cortex
                                                                     0) #Cerebellar nuclei
fig1_heatmap_labsmouse_line_y0 <- rep(0, length.out = length(fig1_heatmap_labsmouse_text))
fig1_heatmap_labsmouse_line_y1 <- fig1_heatmap_labsmouse_text_y - 0.08

#Create the mouse label line grob
fig1_heatmap_labsmouse_line_grob <- segmentsGrob(x0 = unit(fig1_heatmap_labsmouse_line_x0, 'inch'),
                                                 x1 = unit(fig1_heatmap_labsmouse_line_x1, 'inch'),
                                                 y0 = unit(fig1_heatmap_labsmouse_line_y0, 'inch'),
                                                 y1 = unit(fig1_heatmap_labsmouse_line_y1, 'inch'),
                                                 gp = gpar(col = annotation_colours$MouseRegion,
                                                           lwd = 1))

#3. Mouse label title
fig1_heatmap_labsmouse_title_grob <- textGrob("Mouse regions",
                                              x = 0.5, 
                                              y = unit(0.5, 'inch'))

#Combine the mouse label grobs into one
fig1_heatmap_labsmouse_grob <- gTree(children = gList(fig1_heatmap_labsmouse_text_grob,
                                                      fig1_heatmap_labsmouse_line_grob,
                                                      fig1_heatmap_labsmouse_title_grob))



# Figure 1: Heatmap human labels ----------------------------------------------

#1. Human label text
fig1_heatmap_labshuman_text <- treeHuman_16$Get("acronym", filterFun = isLeaf) %>% 
  enframe(name = "Region",
          value = "Acronym") %>% 
  mutate(Region = factor(Region, levels = listLabelsHumanReordered$Region16_reordered)) %>% 
  arrange(Region) %>% 
  pull(Acronym) %>% 
  as.character()

fig1_heatmap_labshuman_text_x <- rep(0.9, length.out = length(fig1_heatmap_labshuman_text))
fig1_heatmap_labshuman_text_y <- c(0.97, #Claustrum
                                   0.92, #Limbic lobe
                                   0.79, #Frontal lobe
                                   0.685, #Insula
                                   0.645, #Occipital lobe
                                   0.59, #Parietal lobe
                                   0.50, #Temporal lobe
                                   0.455, #Amygdala
                                   0.42, #Basal ganglia
                                   0.39, #Basal forebrain
                                   0.355, #Diencephalon
                                   0.31, #Mesencephalon
                                   0.282, #Pons,
                                   0.25, #Myelencephalon,
                                   0.15, #Cerebellar cortex,
                                   0.01) #Cerebellar nuclei
fig1_heatmap_labshuman_text_y <- c(4.850, #Claustrum
                                   4.60, #Limbic lobe
                                   3.950, #Frontal lobe
                                   3.425, #Insula
                                   3.225, #Occipital lobe
                                   2.950, #Parietal lobe
                                   2.5, #Temporal lobe
                                   2.275, #Amygdala
                                   2.10, #Basal ganglia
                                   1.950, #Basal forebrain
                                   1.775, #Diencephalon
                                   1.550, #Mesencephalon
                                   1.410, #Pons,
                                   1.250, #Myelencephalon,
                                   0.750, #Cerebellar cortex,
                                   0.050) #Cerebellar nuclei
fig1_heatmap_labshuman_text_col <- annotation_colours_mod$HumanRegion
fig1_heatmap_labshuman_text_grob <- textGrob(fig1_heatmap_labshuman_text,
                                             x = unit(fig1_heatmap_labshuman_text_x, 'inch'),
                                             y = unit(fig1_heatmap_labshuman_text_y, 'inch'),
                                             just = c("right", "centre"),
                                             gp = gpar(fontsize = 10,
                                                       fontface = "bold",
                                                       col = fig1_heatmap_labshuman_text_col))


#2. Human label lines
# Only need a line for the myelencephalon
fig1_heatmap_labshuman_line_grob <- segmentsGrob(x0 = 0.9, x1 = 1,
                                                 y0 = 0.25, y1 = 0.27,
                                                 gp = gpar(col = annotation_colours$HumanRegion[[14]],
                                                           lwd = 1))

#3. Human label title
fig1_heatmap_labshuman_title_grob <- textGrob("Human regions",
                                              x = 0.4, y = 0.5,
                                              rot = 90)

#Combine the human label grobs into one
fig1_heatmap_labshuman_grob <- gTree(children = gList(fig1_heatmap_labshuman_text_grob,
                                                      fig1_heatmap_labshuman_line_grob,
                                                      fig1_heatmap_labshuman_title_grob))
```

```{r results1-fig1-panelB-sliceseries}
#Set human seed regions
seeds <- c("precentral gyrus",
           "cuneus",
           "crus I")

#Generate a mouse tree with 67 leaf nodes
treeMouse_67 <- Clone(treeMouse)
pruneAnatTree(treeMouse_67,
              nodes = listLabelsMouseReordered$Region67_reordered,
              method = "BelowNode")

#Create a mouse atlas with 67 regions
atlasMouse_67 <- hanatToAtlas(treeMouse_67, mincArray(dsurqeLabels))
dfAtlasMouse_67 <- hanatToAtlasDefs(treeMouse_67)

#Extract seed similarities
dfSeedSim_AllGenes <- matSim_H88M67_AllGenes %>% 
  t() %>% 
  as_tibble(rownames = "Target") %>% 
  select(Target, seeds)

#Convert seed similarities to MINC array
listSeedSim_AllGenes <- map(.x = select(dfSeedSim_AllGenes, -Target),
                            .f = mincBuildArray,
                            labels = atlasMouse_67,
                            defs = dfAtlasMouse_67,
                            values.names = dfSeedSim_AllGenes$Target)

#Apply mask to the background anatomy
dsurqeAnat[dsurqeMask == 0] <- 0

#Create the base slice series
fig1_sliceseries_base <- sliceSeries(nrow = 8, ncol = 1, begin = 70, end = 330) %>% 
  anatomy(mincArray(dsurqeAnat), low = 700, high = 1400) %>%
  overlay(mincArray(listSeedSim_AllGenes[[seeds[1]]]), low = 0.1, high = 0.4, symmetric = TRUE) %>% 
  sliceSeries() %>% anatomy() %>% 
  overlay(mincArray(listSeedSim_AllGenes[[seeds[2]]]), low = 0.1, high = 0.4, symmetric = TRUE) %>%
  sliceSeries() %>% anatomy() %>% 
  overlay(mincArray(listSeedSim_AllGenes[[seeds[3]]]), low = 0.1, high = 0.4, symmetric = TRUE)

#Convert the slice series to grob
fig1_sliceseries_grob <- grobify(fig1_sliceseries_base)

#Generate and extract the legend from the slice series
fig1_sliceseries_legend_grob <- fig1_sliceseries_base %>% 
  legend("Correlation") %>% 
  grobify() %>% 
  getGrob("legend")

#Create text grob for slice series titles
seedColours <- character(length(seeds))
for(i in 1:length(seeds)){
  seedColours[i] <- FindNode(treeHuman, seeds[i])[["color_hex_triplet"]]
}
fig1_sliceseries_labels <- str_to_title(seeds) %>% str_replace("Gyrus", "gyr.")
fig1_sliceseries_labels_grob <- textGrob(fig1_sliceseries_labels,
                                         x = c(0.18, 0.5, 0.845),
                                         y = unit(0.125, 'inch'),
                                         just = "bottom",
                                         gp = gpar(fontsize = 10,
                                                   col = seedColours))
fig1_sliceseries_title_grob <- textGrob("Human seed regions",
                                        x = 0.5, y = unit(0.5, 'inch'))
fig1_sliceseries_text_grob <- gTree(children = gList(fig1_sliceseries_labels_grob,
                                                     fig1_sliceseries_title_grob))
```

```{r results1-fig1-panelC-linechart}
#Convert seed similarity data frame to long form
dfSeedSim_AllGenes_plot <- dfSeedSim_AllGenes %>% 
  gather(key = "Seed", value = "Correlation", -Target) %>% 
  mutate(Seed = factor(Seed, levels = listLabelsHumanReordered$Region88_reordered),
         Target = factor(Target, levels = listLabelsMouseReordered$Region67_reordered)) 

dfSeedSim_Annotations <- dfSeedSim_AllGenes_plot %>% 
  filter(Target %in% c("Primary motor area", "Visual areas", "Crus 1")) %>% 
  mutate(Match = case_when(Target == "Primary motor area" ~ "precentral gyrus",
                           Target == "Visual areas" ~ "cuneus",
                           Target == "Crus 1" ~ "crus I")) %>% 
  filter(Seed == Match)

dfSeedSim_TextColours <- annotation_colours_mod$MouseRegion %>%
  enframe(name = "Region11",
          value = "Colour") %>% 
  inner_join(dfLabelsMouse %>% 
               select(Region11, Region67) %>% 
               distinct(),
             by = "Region11") %>% 
  mutate(Region67 = factor(Region67, levels = listLabelsMouseReordered$Region67_reordered))

#Plot parameters
ylims <- c(-0.3, 0.5)
ybreaks <- seq(-0.2, 0.4, by = 0.2)

#Create base line chart
fig1_linechart <- ggplot(dfSeedSim_AllGenes_plot,
                         aes(x = Target, y = Correlation, col = Seed, group = Seed)) + 
  geom_line() + 
  geom_segment(data = dfSeedSim_Annotations,
               aes(x = Target,
                   xend = Target,
                   y = -Inf,
                   yend = Correlation,
                   col = Seed),
               linetype = "dashed",
               size = 0.8) +
  geom_point(data = dfSeedSim_Annotations) + 
  coord_cartesian(ylim = ylims) + 
  scale_y_continuous(breaks = ybreaks) +
  scale_color_manual(labels = str_replace(str_to_title(seeds), "Gyrus", "gyrus"),
                     values = seedColours) + 
  labs(x = "Mouse region",
       col = "Human seed regions") + 
  theme_bw() +  
  theme(axis.text.x = element_text(angle = 45,
                                   hjust = 1,
                                   size = 6,
                                   colour = dfSeedSim_TextColours$Colour,
                                   face = "bold"),
        plot.margin = margin(t = 0, l = 0, r = 0, b = 0, unit = 'inch'))
fig1_linechart_grob <- ggplotGrob(fig1_linechart) %>% grid.force()

#Extract legend grob from ggplot
fig1_linechart_panel_grob <- getGrob(fig1_linechart_grob, "panel.7-5-7-5")
fig1_linechart_ytext_grob <- getGrob(fig1_linechart_grob, "axis-l.7-4-7-4")
fig1_linechart_ytitle_grob <- getGrob(fig1_linechart_grob, "ylab-l.7-3-7-3")
fig1_linechart_xtext_grob <- getGrob(fig1_linechart_grob, "axis-b.8-5-8-5")
fig1_linechart_xtitle_grob <- getGrob(fig1_linechart_grob, "xlab-b.9-5-9-5")
fig1_linechart_legend_grob <- getGrob(fig1_linechart_grob, "guides.3-3-3-3")
```

```{r results1-fig1-grob}
#Heatmap aspect ratio, figure height and width
matAsp = ncol(matSim_H88M67_AllGenes)/nrow(matSim_H88M67_AllGenes)
matHeight <- 5
matWidth <- matAsp*matHeight

#Slice series width
ssWidth <- matWidth*0.722

#Grob for figure 1
fig1_grob <- arrangeGrob(fig1_heatmap_main_grob, #1
                         fig1_heatmap_legend_grob, #2
                         fig1_heatmap_labsmouse_grob, #3
                         fig1_heatmap_labshuman_grob, #4,
                         fig1_sliceseries_grob, #5
                         fig1_sliceseries_text_grob, #6
                         fig1_sliceseries_legend_grob, #7
                         fig1_linechart_panel_grob,#8
                         fig1_linechart_ytext_grob,#9
                         fig1_linechart_ytitle_grob,#10
                         fig1_linechart_xtext_grob, #11
                         fig1_linechart_xtitle_grob,#12
                         fig1_linechart_legend_grob,#13
                         layout_matrix = rbind(c(NA, NA, NA,  3, NA, NA,  6, NA),
                                               c( 4,  4,  4,  1, NA,  2,  5,  7),
                                               c(NA, NA, NA, NA, NA, NA, NA, NA),
                                               c(NA, 10,  9,  8,  8,  8,  8, 13),
                                               c(NA, NA, NA, 11, 11, 11, 11, NA),
                                               c(NA, NA, NA, 12, 12, 12, 12, NA)),
                         widths = unit(c(0.4, 0.3, 0.3, matWidth, 0.08, 0.78, ssWidth, 1.73), 'inch'),
                         heights = unit(c(0.7, matHeight, 0.3, 1.1, 1.1, 0.2), 'inch'))
```

```{r results1-fig1-interactive, include=TRUE, echo = FALSE, fig.width=10, fig.height = 8.6}
grid.newpage()
grid.draw(fig1_grob)
grid.text(c("A.", "B.", "C."),
          x = unit(c(0.25, 5.25, 0.25), 'inch'), 
          y = unit(c(8.299, 8.299, 2.55), 'inch'),
          gp = gpar(fontsize = 14, fontface = "bold"))
sliceAMBAWidth <- 1.1
sliceAMBAHeight <- sliceAMBAWidth/asp
vp = viewport(x = unit(9.15, 'inch'),
              y = unit(0.8, 'inch'),
              width = unit(sliceAMBAWidth, 'inch'),
              height = unit(sliceAMBAHeight, 'inch'))
pushViewport(vp)
grid.draw(sliceAMBALegend_panel_grob)
popViewport()
grid.rect(gp = gpar(fill = NA))
```

```{r results1-fig1-write}
fileout <- str_c(pathHome, "Draft/", "Version3/", "Figure1.RData")
save(fig1_grob,
     sliceAMBALegend_panel_grob,
     file = fileout)
```
