---
title: "Untitled"
author: "Antoine Beauchamp"
date: "November 10, 2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r libraries}
#Libraries
suppressPackageStartupMessages(library(tidyverse))
library(grid)
library(gridExtra)
library(pheatmap)
library(ggplotify)
library(ggnewscale)
library(RMINC)
library(MRIcrotome)
library(data.tree)
library(RColorBrewer)
```

```{r functions}
#Functions
source("/projects/abeauchamp/Functions/TreeTools.R")
source("/projects/abeauchamp/Functions/mincBuildArray.R")
source("/projects/abeauchamp/Projects/MouseHumanMapping/Functions/ProcessingTools.R")
source("/projects/abeauchamp/Projects/MouseHumanMapping/Functions/buildSimilarityMatrix.R")
```

```{r import}
#Set path
pathHome <- "/projects/abeauchamp/Projects/MouseHumanMapping/Paper_Descriptive/"

#Import data
dfExprMouse <- suppressMessages(read_csv(str_c(pathHome, "Data/", "MouseExpressionMatrix_Voxel_coronal_maskcoronal_imputed_labelled.csv")))
dfExprHuman <- suppressMessages(read_csv(str_c(pathHome, "Data/", "HumanExpressionMatrix_Samples_labelled.csv")))

#Load mouse/human labels (Objects: listLabelsMouseReordered, listLabelsHumanReordered)
load(str_c(pathHome, "Data/", "TreeLabelsReordered.RData"))

#Import MICe data tree
load(str_c("/projects/abeauchamp/Projects/MouseHumanMapping/AllenMouseBrainAtlas/Data/MouseExpressionTree_DSURQE.RData"))
treeMouse <- Clone(treeMouseExpr)
rm(treeMouseExpr)

#Remove white matter and ventricles
pruneAnatTree(treeMouse, 
              nodes = c("fiber tracts", "ventricular systems"),
              method = "AtNode")

#Import AHBA data tree
load("/projects/abeauchamp/Projects/MouseHumanMapping/AllenHumanBrainAtlas/Data/HumanExpressionTree_Samples.RData")
treeHuman <- Clone(treeHumanExpr)
rm(treeHumanExpr)

#Fix human colour names (need to start with #)
treeHuman$Do(function(node){
  node$color_hex_triplet <- str_c("#", node$color_hex_triplet)
})

#Remove white matter and ventricles
pruneAnatTree(treeHuman,
              nodes = c("white matter", "sulci & spaces"),
              method = "AtNode")

#Import DSURQE labels and template
dsurqeLabels <- mincGetVolume("/projects/abeauchamp/Atlases/DSURQE/DSURQE_40micron_labels.mnc")
dsurqeAnat <- mincGetVolume("/projects/abeauchamp/Atlases/DSURQE/DSURQE_40micron_average.mnc")
dsurqeMask <- mincGetVolume("/projects/abeauchamp/Atlases/DSURQE/DSURQE_40micron_mask.mnc")
```

```{r normalization}
#Extract labels from data frames
dfLabelsMouse <- dfExprMouse %>% select(contains("Region"))
dfLabelsHuman <- dfExprHuman %>% select(contains("Region"))

# #Normalize mouse data
# dfExprMouse_scaled <- dfExprMouse %>% 
#   select(-contains("Region")) %>% 
#   as.matrix() %>% 
#   scaler(axis = "rows") %>% 
#   scaler(scale = FALSE, axis = "columns") %>% 
#   as_tibble() %>% 
#   bind_cols(dfLabelsMouse)
# 
# #Normalize human data
# dfExprHuman_scaled <- dfExprHuman %>% 
#   select(-contains("Region")) %>% 
#   as.matrix() %>% 
#   scaler(axis = "rows") %>% 
#   scaler(scale = FALSE, axis = "columns") %>% 
#   as_tibble() %>% 
#   bind_cols(dfLabelsHuman)

#Extract genes list from mouse data (same as human)
# genes <- colnames(dfExprMouse_scaled)[!str_detect(colnames(dfExprMouse_scaled), "Region")]

rm(dfExprMouse, dfExprHuman)
```

```{r results2-fig2-processing}
#Path to MLP files
pathMLP <- str_c(pathHome, "Data/MultilayerPerceptronOutcomes/")

#Files containing latent space representations
filesMLP_Mouse <- list.files(pathMLP, pattern = "MouseTx", full.names = T)
filesMLP_Human <- list.files(pathMLP, pattern = "HumanTx", full.names = T)

#Import the mouse latent space data
listMouseLatentSpace <- map(filesMLP_Mouse,
                            function(x){
                              suppressMessages(read_csv(x)) %>% 
                                column_to_rownames("Region") %>% 
                                as.matrix() %>% 
                                t()
                            })

#Import the human latent space data
listHumanLatentSpace <- map(filesMLP_Human,
                            function(x){
                              suppressMessages(read_csv(x)) %>% 
                                column_to_rownames("Region") %>% 
                                as.matrix() %>% 
                                t()
                            })

#Compute the latent space similarity matrices
listSimLatentSpace <- map2(listHumanLatentSpace, listMouseLatentSpace,
                           function(x1, x2){
                             m <- buildSimilarityMatrix(x1 = x1, x2 = x2)
                             m <- m[,match(listLabelsMouseReordered$Region67_reordered, colnames(m))]
                             m <- m[match(listLabelsHumanReordered$Region88_reordered, rownames(m)),]
                           })
names(listSimLatentSpace) <- str_c("MLP_v", 1:length(listSimLatentSpace))
rm(listMouseLatentSpace, listHumanLatentSpace)
```

```{r}
matMaxSim_Mouse <- matrix(0,
                          nrow = length(listLabelsMouseReordered$Region67_reordered),
                          ncol = length(listSimLatentSpace),
                          dimnames = list(listLabelsMouseReordered$Region67_reordered,
                                          names(listSimLatentSpace)))
matMaxSim_Human <- matrix(0, 
                          nrow = length(listLabelsHumanReordered$Region88_reordered),
                          ncol = length(listSimLatentSpace),
                          dimnames = list(listLabelsHumanReordered$Region88_reordered,
                                          names(listSimLatentSpace)))

for(l in 1:length(listSimLatentSpace)){
  matMaxSim_Human[, l] <- apply(listSimLatentSpace[[l]], MARGIN = 1, FUN = max)
  matMaxSim_Mouse[, l] <- apply(listSimLatentSpace[[l]], MARGIN = 2, FUN = max)
}

dfMaxSim_Human <- matMaxSim_Human %>% 
  as_tibble(rownames = "Region") %>% 
  pivot_longer(cols = -Region, names_to = "Data", values_to = "MaxSimilarity")

dfMaxSim_Mouse <- matMaxSim_Mouse %>% 
  as_tibble(rownames = "Region") %>% 
  pivot_longer(cols = -Region, names_to = "Data", values_to = "MaxSimilarity")

sampleLatentSpace <- sample(names(listSimLatentSpace), size = 250)
dfMaxSim_Human_Sample <- dfMaxSim_Human %>% 
  filter(Data %in% sampleLatentSpace)

dfMaxSim_Mouse_Sample <- dfMaxSim_Mouse %>% 
  filter(Data %in% sampleLatentSpace)

dfMaxSim_Compare_Sample <- bind_rows(dfMaxSim_Human_Sample %>% 
                                       mutate(Species = "Human"),
                                     dfMaxSim_Mouse_Sample %>% 
                                       mutate(Species = "Mouse"))
```

```{r fig.height = 6, fig.width = 8}
ggplot(dfMaxSim_Compare_Sample, aes(x = MaxSimilarity, group = Data)) + 
  geom_density(size = 0.05,
               col = "grey50",
               alpha = 0.3) + 
  facet_wrap(~Species, nrow = 2) + 
  coord_cartesian(xlim = c(0.4, 1)) + 
  scale_x_continuous(breaks = seq(0, 1, by = 0.1)) + 
  labs(x = "Maximal correlation",
       y = "Density",
       caption = "Each line is a latent space. 250 spaces sampled.",
       title = "Distributions of maximal correlation for ROIs in the mouse and human") + 
  theme_bw()
```


```{r}
treeMouse_67 <- Clone(treeMouse)
pruneAnatTree(treeMouse_67,
              nodes = listLabelsMouseReordered$Region67_reordered,
              method = "BelowNode")
coloursMouse <- treeMouse_67$Get("color_hex_triplet", filterFun = isLeaf) %>% 
  enframe(name = "Region", value = "Colour") %>% 
  mutate(Region = factor(Region, levels = listLabelsMouseReordered$Region67_reordered)) %>% 
  arrange(Region) %>% 
  pull(Colour)

dfMaxSim_Mouse <- dfMaxSim_Mouse %>% 
  mutate(Region = factor(Region, levels = listLabelsMouseReordered$Region67_reordered))
ggplot(dfMaxSim_Mouse, aes(x = MaxSimilarity, col = Region)) + 
  geom_density(show.legend = F,
               # col = "grey70",
               alpha = 0.3) + 
  scale_colour_manual(values = coloursMouse) + 
  theme_bw()
```

