---
title: "Untitled"
author: "Antoine Beauchamp"
date: '2022-07-15'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(data.tree)
library(pheatmap)
suppressPackageStartupMessages(library(RColorBrewer))
suppressPackageStartupMessages(library(ggplotify))
```

```{r}
source("../../../functions/tree_tools.R")
source("../../../functions/buildSimilarityMatrix.R")
```

```{r import-basic}
#Import data
dfExprMouse <- suppressMessages(read_csv("../../../data/MouseExpressionMatrix_voxel_coronal_maskcoronal_log2_grouped_imputed_labelled.csv"))
dfExprHuman <- suppressMessages(read_csv("../../../data/HumanExpressionMatrix_samples_pipeline_abagen_labelled.csv"))

#Extract labels from data frames
dfLabelsMouse <- dfExprMouse %>% select(contains("Region"))
dfLabelsHuman <- dfExprHuman %>% select(contains("Region"))

#Remove expression data frames
rm(dfExprMouse, dfExprHuman)

#Load mouse/human labels (Objects: listLabelsMouseReordered, listLabelsHumanReordered)
load("../../../data/TreeLabelsReordered.RData")

#Import MICe data tree
load("../../../AMBA/data/MouseExpressionTree_DSURQE.RData")
treeMouse <- Clone(treeMouseExpr)
rm(treeMouseExpr)

#Remove white matter and ventricles
pruneAnatTree(treeMouse, 
              nodes = c("fiber tracts", "ventricular systems"),
              method = "AtNode")

#Import AHBA data tree
load("../../../AHBA/data/HumanExpressionTree.RData")
treeHuman <- Clone(treeHumanExpr)
rm(treeHumanExpr)

#Fix human colour names (need to start with #)
treeHuman$Do(function(node){
  node$color_hex_triplet <- str_c("#", node$color_hex_triplet)
})

#Remove white matter and ventricles
pruneAnatTree(treeHuman,
              nodes = c("white matter", "sulci & spaces"),
              method = "AtNode")
```

```{r results2-fig2-panelC-heatmap-processing}
#Create annotation data frame for mouse regions
#Annotations use 11 coarser brain ROIs
dfAnnotationMouse <- dfLabelsMouse %>% 
  select(Region67, Region11) %>% 
  distinct() %>% 
  column_to_rownames("Region67") %>% 
  rename(MouseRegion = Region11)

#Order mouse annotations according to brain organization
indOrderMouse <- match(listLabelsMouseReordered$Region67_reordered, rownames(dfAnnotationMouse))
dfAnnotationMouse$MouseRegion <- dfAnnotationMouse$MouseRegion[indOrderMouse]
rownames(dfAnnotationMouse) <- rownames(dfAnnotationMouse)[indOrderMouse]

dfAnnotationMouse$MouseRegion <- factor(dfAnnotationMouse$MouseRegion, levels = listLabelsMouseReordered$Region11_reordered)

#Repeat for human regions
dfAnnotationHuman <- dfLabelsHuman %>% 
  select(Region88, Region16) %>% 
  distinct() %>% 
  column_to_rownames("Region88") %>% 
  rename(HumanRegion = Region16)

indOrderHuman <- match(listLabelsHumanReordered$Region88_reordered, rownames(dfAnnotationHuman))
dfAnnotationHuman$HumanRegion <- dfAnnotationHuman$HumanRegion[indOrderHuman]
rownames(dfAnnotationHuman) <- rownames(dfAnnotationHuman)[indOrderHuman]

dfAnnotationHuman$HumanRegion <- factor(dfAnnotationHuman$HumanRegion, levels = listLabelsHumanReordered$Region16_reordered)

#Prune mouse tree to 11 regions for cluster annotations
treeMouse_11 <- Clone(treeMouse)
pruneAnatTree(treeMouse_11,
              nodes = listLabelsMouseReordered$Region11,
              method = "BelowNode")

#Prune human tree to 16 regions for cluster annotations
treeHuman_16 <- Clone(treeHuman) 
pruneAnatTree(treeHuman_16,
              nodes = listLabelsHumanReordered$Region16,
              method = "BelowNode")

#Get colour annotation from trees
coloursMouse <-  treeMouse_11$Get("color_hex_triplet", filterFun = isLeaf)
indOrderMouseColours <- match(listLabelsMouseReordered$Region11_reordered, names(coloursMouse))
coloursMouse <- coloursMouse[indOrderMouseColours]

coloursHuman <- treeHuman_16$Get("color_hex_triplet", filterFun = isLeaf)
indOrderHumanColours <- match(listLabelsHumanReordered$Region16_reordered, names(coloursHuman))
coloursHuman <- coloursHuman[indOrderHumanColours]

annotation_colours <- list(MouseRegion = coloursMouse,
                           HumanRegion = coloursHuman)

#Create a set of modified colours for clearer visualization. 
#To be used for text colouring mostly
annotation_colours_mod <- annotation_colours
annotation_colours_mod$MouseRegion["Isocortex"] <- "#68EC68"
annotation_colours_mod$MouseRegion["Cerebellar cortex"] <- "#E6E67B"
annotation_colours_mod$MouseRegion["Cerebellar nuclei"] <- "#E6E67B"

annotation_colours_mod$HumanRegion["insula"] <- "#E6E658"
annotation_colours_mod$HumanRegion["diencephalon"] <- "#85DD63"
annotation_colours_mod$HumanRegion["pons"] <- "#00E0A4"
```

```{r}
labelsCortexMouse <- dfLabelsMouse %>% 
  filter(Region11 == 'Isocortex') %>% 
  select(Region67) %>% 
  distinct() %>% 
  pull()

structsHuman_Cx_16 <- c("limbic lobe", "frontal lobe", "insula", "occipital lobe","parietal lobe", "temporal lobe")
labelsCortexHuman <- dfLabelsHuman %>% 
  filter(Region16 %in% structsHuman_Cx_16) %>% 
  filter(!(Region88 %in% c("claustrum", "dentate gyrus", "CA1 field", "CA2 field", "CA3 field", "CA4 field", "subiculum"))) %>% 
  select(Region16, Region88) %>% 
  distinct() %>% 
  pull(Region88)
```

```{r}
#Some values to set up the palette
paletteLength <- 255 #Palette length
heatmapRange <- c(-0.3, 1) #Heatmap range
heatmapRangeDist <- heatmapRange[2] - heatmapRange[1] #Range distance
distNegative <- abs(heatmapRange[1] - 0) #Negative distance
percNegative <- distNegative/heatmapRangeDist #Percent of range negative
lengthNegative <- floor(percNegative*paletteLength) #Number of negative elements
lengthPositive <- paletteLength - lengthNegative #Number of positive elements

#Create the palette
heatmapColours <- rev(brewer.pal(n = 11, name = "RdYlBu")) #Palette colours
heatmapPaletteNegative <- colorRampPalette(heatmapColours[1:6])(lengthNegative) #Negative palette
heatmapPalettePositive <- colorRampPalette(heatmapColours[6:11])(lengthPositive) #Positive palette
heatmapPalette <- c(heatmapPaletteNegative, heatmapPalettePositive) #Full palette

#Heatmap breaks
heatmapBreaks <- seq(heatmapRange[1], heatmapRange[2], length.out = paletteLength)
```

```{r}
heatmapPalette_cluster <- magma(n = 100, direction = 1, begin = 0.35) #Not bad
```



# Isocortical subtree

```{r import-latent-space}
#Path to MLP files
pathMLP <- "../../../data/MLP_outcomes_isocortex/"

#Files containing latent space representations
filesMLP_Mouse <- list.files(pathMLP, pattern = "MouseTx", full.names = T)
filesMLP_Human <- list.files(pathMLP, pattern = "HumanTx", full.names = T)

#Import the mouse latent space data
listMouseLatentSpace <- map(filesMLP_Mouse,
                            function(x){
                              suppressMessages(read_csv(x)) %>% 
                                column_to_rownames("Region") %>% 
                                as.matrix() %>% 
                                t()
                            })

#Import the human latent space data
listHumanLatentSpace <- map(filesMLP_Human,
                            function(x){
                              suppressMessages(read_csv(x)) %>% 
                                column_to_rownames("Region") %>% 
                                as.matrix() %>% 
                                t()
                            })

listSimLatentSpace <- map2(listHumanLatentSpace, listMouseLatentSpace,
                           function(x1, x2){
                             m <- buildSimilarityMatrix(x1 = x1, x2 = x2)
                             m <- m[,match(listLabelsMouseReordered$Region67_reordered, colnames(m))]
                             m <- m[match(listLabelsHumanReordered$Region88_reordered, rownames(m)),]
                           })
names(listSimLatentSpace) <- str_c("MLP_v", 1:length(listSimLatentSpace))
rm(listMouseLatentSpace, listHumanLatentSpace)

#To create an average similarity matrix, first concat the similarity matrices into a 3D array
arraySimLatentSpace <- array(unlist(listSimLatentSpace),
                             dim = c(length(listLabelsHumanReordered$Region88_reordered),
                                     length(listLabelsMouseReordered$Region67_reordered),
                                     length(listSimLatentSpace)))

#Compute the average matrix
matSim_H88M67_MLP_mean_subtree <- rowMeans(arraySimLatentSpace, dims = 2)
rownames(matSim_H88M67_MLP_mean_subtree) <- listLabelsHumanReordered$Region88_reordered
colnames(matSim_H88M67_MLP_mean_subtree) <- listLabelsMouseReordered$Region67_reordered
```

```{r}
matSim_H88M67_MLP_mean_subtree <- matSim_H88M67_MLP_mean_subtree[,colnames(matSim_H88M67_MLP_mean_subtree) %in% labelsCortexMouse]
matSim_H88M67_MLP_mean_subtree <- matSim_H88M67_MLP_mean_subtree[rownames(matSim_H88M67_MLP_mean_subtree) %in% labelsCortexHuman,]
```

```{r}
#Generate similarity matrix heatmap and convert to ggplot object
fig2_heatmap_ggplot <- pheatmap(matSim_H88M67_MLP_mean_subtree,
                                color = heatmapPalette,
                                breaks = heatmapBreaks,
                                cluster_cols = F, cluster_rows = F,
                                border_color = "white",
                                show_rownames = T, show_colnames = T,
                                annotation_row = dfAnnotationHuman,
                                annotation_col = dfAnnotationMouse,
                                annotation_colors = annotation_colours,
                                legend = ,
                                annotation_legend = F,
                                annotation_names_col = F, annotation_names_row = F) %>% 
  as.ggplot()
```

```{r}
#Compute the average matrix
matSim_H88M67_MLP_sd <- apply(arraySimLatentSpace, c(1,2), FUN = sd)
rownames(matSim_H88M67_MLP_sd) <- listLabelsHumanReordered$Region88_reordered
colnames(matSim_H88M67_MLP_sd) <- listLabelsMouseReordered$Region67_reordered
```

```{r}
#Generate similarity matrix heatmap and convert to ggplot object
fig2_heatmap_ggplot <- pheatmap(matSim_H88M67_MLP_sd,
                                # color = heatmapPalette,
                                # breaks = heatmapBreaks,
                                cluster_cols = F, cluster_rows = F,
                                border_color = "white",
                                show_rownames = F, show_colnames = F,
                                annotation_row = dfAnnotationHuman,
                                annotation_col = dfAnnotationMouse,
                                annotation_colors = annotation_colours,
                                legend = ,
                                annotation_legend = F,
                                annotation_names_col = F, annotation_names_row = F) %>% 
  as.ggplot()
```


```{r}
fig5_heatmap_ggplot <- pheatmap(mat = t(matSim_H88M67_MLP_mean_subtree), 
                                cluster_cols = T, cluster_rows = T,
                                cutree_rows = 4, cutree_cols = 4,
                                treeheight_col = 30, treeheight_row = 30,
                                color = heatmapPalette_cluster,
                                legend = F, 
                                # annotation_row = dfAnnotations,
                                # annotation_legend = T,
                                annotation_names_row = F, 
                                annotation_colors = heatmapAnnotationColours,
                                fontsize_row = 6, fontsize_col = 6) %>% 
  as.ggplot()
```



# Whole brain

```{r import-latent-space}
#Path to MLP files
pathMLP <- "../../../data/MLP_outcomes/"

#Files containing latent space representations
filesMLP_Mouse <- list.files(pathMLP, pattern = "MouseTx", full.names = T)
filesMLP_Human <- list.files(pathMLP, pattern = "HumanTx", full.names = T)
```


```{r import-latent-space}
#Import the mouse latent space data
listMouseLatentSpace <- map(filesMLP_Mouse,
                            function(x){
                              suppressMessages(read_csv(x)) %>% 
                                column_to_rownames("Region") %>% 
                                as.matrix() %>% 
                                t()
                            })

#Import the human latent space data
listHumanLatentSpace <- map(filesMLP_Human,
                            function(x){
                              suppressMessages(read_csv(x)) %>% 
                                column_to_rownames("Region") %>% 
                                as.matrix() %>% 
                                t()
                            })
```

```{r}
listSimLatentSpace <- map2(listHumanLatentSpace, listMouseLatentSpace,
                           function(x1, x2){
                             m <- buildSimilarityMatrix(x1 = x1, x2 = x2)
                             m <- m[,match(listLabelsMouseReordered$Region67_reordered, colnames(m))]
                             m <- m[match(listLabelsHumanReordered$Region88_reordered, rownames(m)),]
                           })
names(listSimLatentSpace) <- str_c("MLP_v", 1:length(listSimLatentSpace))
rm(listMouseLatentSpace, listHumanLatentSpace)
```

```{r}
#To create an average similarity matrix, first concat the similarity matrices into a 3D array
arraySimLatentSpace <- array(unlist(listSimLatentSpace),
                             dim = c(length(listLabelsHumanReordered$Region88_reordered),
                                     length(listLabelsMouseReordered$Region67_reordered),
                                     length(listSimLatentSpace)))

#Compute the average matrix
matSim_H88M67_MLP_mean <- rowMeans(arraySimLatentSpace, dims = 2)
rownames(matSim_H88M67_MLP_mean) <- listLabelsHumanReordered$Region88_reordered
colnames(matSim_H88M67_MLP_mean) <- listLabelsMouseReordered$Region67_reordered
```

```{r}
matSim_H88M67_MLP_mean <- matSim_H88M67_MLP_mean[,colnames(matSim_H88M67_MLP_mean) %in% labelsCortexMouse]
matSim_H88M67_MLP_mean <- matSim_H88M67_MLP_mean[rownames(matSim_H88M67_MLP_mean) %in% labelsCortexHuman,]
```

```{r}
#Generate similarity matrix heatmap and convert to ggplot object
fig2_heatmap_ggplot <- pheatmap(matSim_H88M67_MLP_mean,
                                color = heatmapPalette,
                                breaks = heatmapBreaks,
                                cluster_cols = F, cluster_rows = F,
                                border_color = "white",
                                show_rownames = T, show_colnames = T,
                                annotation_row = dfAnnotationHuman,
                                annotation_col = dfAnnotationMouse,
                                annotation_colors = annotation_colours,
                                legend = ,
                                annotation_legend = F,
                                annotation_names_col = F, annotation_names_row = F) %>% 
  as.ggplot()
```

```{r}
fig5_heatmap_ggplot <- pheatmap(mat = t(matSim_H88M67_MLP_mean), 
                                cluster_cols = T, cluster_rows = T,
                                cutree_rows = 4, cutree_cols = 4,
                                treeheight_col = 30, treeheight_row = 30,
                                color = heatmapPalette,
                                legend = T, 
                                # annotation_row = dfAnnotations,
                                # annotation_legend = T,
                                annotation_names_row = F, 
                                annotation_colors = heatmapAnnotationColours,
                                fontsize_row = 6, fontsize_col = 6) %>% 
  as.ggplot()
```

