---
title: "Untitled"
author: "Antoine Beauchamp"
date: "14/02/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
suppressPackageStartupMessages(library(tidyverse))
library(data.tree)
```

```{r}
source("/projects/abeauchamp/Functions/TreeTools.R")
source("/projects/abeauchamp/Projects/MouseHumanMapping/Functions/buildSimilarityMatrix.R")
```


```{r import}
#Set path
pathHome <- "/projects/abeauchamp/Projects/MouseHumanMapping/Paper_Descriptive/"

#Import data
dfExprMouse <- suppressMessages(read_csv(str_c(pathHome, "Data/", "MouseExpressionMatrix_Voxel_coronal_maskcoronal_imputed_labelled.csv")))
dfExprHuman <- suppressMessages(read_csv(str_c(pathHome, "Data/", "HumanExpressionMatrix_Samples_labelled.csv")))

#Load mouse/human labels (Objects: listLabelsMouseReordered, listLabelsHumanReordered)
load(str_c(pathHome, "Data/", "TreeLabelsReordered.RData"))

#Import MICe data tree
load(str_c("/projects/abeauchamp/Projects/MouseHumanMapping/AllenMouseBrainAtlas/Data/MouseExpressionTree_DSURQE.RData"))
treeMouse <- Clone(treeMouseExpr)
rm(treeMouseExpr)

#Remove white matter and ventricles
pruneAnatTree(treeMouse, 
              nodes = c("fiber tracts", "ventricular systems"),
              method = "AtNode")

#Import AHBA data tree
load("/projects/abeauchamp/Projects/MouseHumanMapping/AllenHumanBrainAtlas/Data/HumanExpressionTree_Samples.RData")
treeHuman <- Clone(treeHumanExpr)
rm(treeHumanExpr)

#Fix human colour names (need to start with #)
treeHuman$Do(function(node){
  node$color_hex_triplet <- str_c("#", node$color_hex_triplet)
})

#Remove white matter and ventricles
pruneAnatTree(treeHuman,
              nodes = c("white matter", "sulci & spaces"),
              method = "AtNode")
```

```{r}
#Extract labels from data frames
dfLabelsMouse <- dfExprMouse %>% 
  select(contains("Region")) %>% 
  mutate(VoxelID = str_c("V", 1:nrow(.)))
dfLabelsHuman <- dfExprHuman %>% 
  select(contains("Region")) %>% 
  mutate(SampleID = str_c("S", 1:nrow(.)))
```

```{r}
#Path to MLP files
pathMLP <- str_c(pathHome, "Data/MultilayerPerceptronOutcomes")

structsHuman_Cx_16 <- c("limbic lobe", "frontal lobe", "insula", "occipital lobe","parietal lobe", "temporal lobe")

#Takes about 30 minutes to run
runSimMat <- FALSE
if(runSimMat){
  
  filesMLP_Mouse <- list.files(pathMLP, pattern = "MouseVoxelTx", full.names = T)
  filesMLP_Human <- list.files(pathMLP, pattern = "HumanVoxelTx", full.names = T)
  
  computeSimilarityMatrix <- function(mouse, human){
    
    matHuman <- suppressMessages(read_csv(human, progress = F)) %>% 
      select(-Region) %>% 
      mutate(SampleID = str_c("S", 1:nrow(.))) %>% 
      inner_join(dfLabelsHuman %>% 
                   select(SampleID, Region16, Region88, Region166),
                 by = "SampleID") %>% 
      filter(Region16 %in% structsHuman_Cx_16,
             !(Region88 %in% c("claustrum", "dentate gyrus", "CA1 field", "CA2 field", "CA3 field", "CA4 field", "subiculum"))) %>% 
      select(-SampleID, -Region16, -Region88) %>%
      rename(Region = Region166) %>% 
      group_by(Region) %>% 
      summarise_all(mean) %>% 
      ungroup() %>% 
      column_to_rownames("Region") %>% 
      as.matrix() %>% 
      t()
    
    matMouse <- suppressMessages(read_csv(mouse, progress = F)) %>% 
      select(-Region) %>% 
      mutate(VoxelID = str_c("V", 1:nrow(.))) %>% 
      inner_join(dfLabelsMouse %>% 
                   select(VoxelID, Region11, Region67),
                 by = "VoxelID") %>% 
      filter(Region11 == "Isocortex") %>% 
      rename(Region = Region67) %>% 
      select(-VoxelID, -Region11) %>% 
      group_by(Region) %>% 
      summarise_all(mean) %>% 
      ungroup() %>% 
      column_to_rownames("Region") %>% 
      as.matrix() %>% 
      t()
    
    matSim <- buildSimilarityMatrix(x1 = matHuman,
                                    x2 = matMouse,
                                    method = "correlation")
    
    return(matSim)
    
  }
  
  ti <- Sys.time()
  listSimCortex <- map2(.x = filesMLP_Mouse,
                        .y = filesMLP_Human,
                        .f = computeSimilarityMatrix)
  names(listSimCortex) <- str_c("MLP", 1:length(listSimCortex))
  
  save(listSimCortex,
       file = str_c(pathHome, "Data/", "CortexSimilarityMatrices.RData"))
  
  tf <- Sys.time()  
  
  print(tf-ti)
} else {
  load(str_c(pathHome, "Data/", "CortexSimilarityMatrices.RData"))
}
```


```{r}
#' Compute scaled similarity profiles for every column in a similarity matrix
#'
#' @param similarity A similarity matrix
#' @param scale A logical value indicating whether to scale the similarity profiles
#'
#' @return A tibble containing the scaled similarity profiles
computeSimilarityProfiles <- function(similarity, scale = FALSE){
  
  profiles <- tibble()
  for(seed in colnames(similarity)){
    temp <- similarity[, seed] %>% 
      enframe(name = "Target",
              value = "Similarity") 
    
    if(scale){
      temp <- temp %>% 
        mutate(Similarity = (Similarity - min(Similarity))/(max(Similarity) - min(Similarity)))
    }
    
    temp <- temp %>% 
      mutate(TargetRank = as.numeric(factor(Target, levels = Target[order(Similarity, decreasing = TRUE)])),
             Seed = seed)
    profiles <- bind_rows(profiles, temp)
  }
  return(profiles)
}

dfSimilarityProfiles <- map(.x = listSimCortex,
                            .f = t) %>% 
  map_dfr(.f = computeSimilarityProfiles,
          .id = "Data")
```

```{r}
head(dfSimilarityProfiles)
```

```{r}
structsHuman_PFC <- c("cingulate gyrus, frontal part",
                      "subcallosal cingulate gyrus",
                      "superior frontal gyrus",
                      "frontal pole")

structsHuman_PFC_agranular <- c("cingulate gyrus, frontal part",
                               "subcallosal cingulate gyrus")
structsHuman_PFC_granular <- structsHuman_PFC[!(structsHuman_PFC %in% structsHuman_PFC_agranular)]

```

```{r fig.height = 3, fig.width = 4}
dfSimilarityProfiles_PFC_MaxSim <- dfSimilarityProfiles %>% 
  group_by(Data, Seed) %>% 
  filter(Similarity == max(Similarity)) %>% 
  ungroup()

dfSimilarityProfiles_PFC_MaxSim_Summary <- dfSimilarityProfiles_PFC_MaxSim %>% 
  group_by(Seed) %>% 
  summarise(SimilarityMean = mean(Similarity),
            SimilaritySdLower = SimilarityMean - 2*sd(Similarity),
            SimilaritySdUpper = SimilarityMean + 2*sd(Similarity)) %>% 
  ungroup() %>% 
  mutate(Seed = factor(Seed, levels = Seed[order(SimilarityMean)]),
         CortexType = case_when(Seed %in% structsHuman_PFC_agranular ~ "Agranular",
                                Seed %in% structsHuman_PFC_granular ~ "Granular",
                                !(Seed %in% structsHuman_PFC) ~ "Other"))

ggplot(dfSimilarityProfiles_PFC_MaxSim_Summary,
       aes(x = Seed,
           y = SimilarityMean,
           ymin = SimilaritySdLower,
           ymax = SimilaritySdUpper,
           col = CortexType)) + 
  geom_pointrange(size = 0.3) + 
  coord_flip(ylim = c(0.7, 1)) + 
  scale_y_continuous(breaks = seq(0.7, 1, by = 0.02)) + 
  scale_color_manual(labels = c("Agranular", "Granular", "Not annotated"),
                     values = c(RColorBrewer::brewer.pal(3, name = "Set1")[1:2], "grey70")) + 
  labs(x = "Human cortical regions",
       y = "Maximal correlation",
       col = "Type of cortex",
       title = "Distributions of maximal correlation for human cortical regions") + 
  theme_bw() + 
  theme(axis.text.y = element_text(size = 8))
```

```{r}
dfSimilarityProfiles_PFC_MaxSim_Compare <- dfSimilarityProfiles_PFC_MaxSim %>% 
  mutate(CortexType = ifelse(Seed %in% structsHuman_PFC_agranular, "Agranular", "Granular")) %>% 
  group_by(Data, CortexType) %>% 
  summarise(SimilarityMean = mean(Similarity)) %>% 
  ungroup()

ggplot(dfSimilarityProfiles_PFC_MaxSim_Compare, aes(x = CortexType, y = SimilarityMean, col = CortexType)) + 
  geom_line(aes(group = Data),
            col = "grey70",
            size = 0.5,
            alpha = 0.05) + 
  geom_boxplot(outlier.size = 0.5,
               alpha = 0.6) + 
  coord_cartesian(ylim = c(0.8, 1)) + 
  scale_y_continuous(breaks = seq(0.8, 1, by = 0.02)) + 
  scale_color_manual(labels = c("Agranular", "Granular"),
                     values = RColorBrewer::brewer.pal(n = 3, name = "Set1")[1:2]) + 
  labs(x = "Type of cortex",
       y = "Average maximal correlation",
       col = "Type of cortex",
       title = "Distributions of maximal correlation per cortex type",
       caption = "Each line is a latent space") + 
  theme_bw()
```

```{r}
library(lme4)
modelCx <- lmer(SimilarityMean ~ CortexType + (1|Data), data = dfSimilarityProfiles_PFC_MaxSim_Compare)
summary(modelCx)
```




```{r}
matSim_MLP <- dfSimilarityProfiles %>% 
  group_by(Seed, Target) %>% 
  summarise(SimilarityMean = mean(Similarity)) %>% 
  ungroup() %>% 
  filter(Seed %in% structsHuman_PFC) %>% 
  pivot_wider(id_cols = Target, names_from = Seed, values_from = SimilarityMean) %>% 
  column_to_rownames("Target") %>% 
  as.matrix()

mouseOrder <- c("Infralimbic area",
                "Perirhinal area",
                "Agranular insular area",
                "Ectorhinal area",
                "Orbital area",
                "Prelimbic area",
                "Frontal pole, cerebral cortex",
                "Temporal association areas",
                "Retrosplenial area",
                "Primary somatosensory area",
                "Posterior parietal association areas",
                "Visual areas",
                "Dorsal auditory area",
                "Primary motor area",
                "Supplemental somatosensory area",
                "Ventral auditory area",
                "Anterior cingulate area",
                "Primary auditory area",
                "Secondary motor area")

matSim_MLP <- matSim_MLP[match(mouseOrder, rownames(matSim_MLP)),] 

library(viridis)
heatmapPalette <- magma(n = 100, direction = 1, begin = 0.35)

```

```{r fig.height = 3, fig.width = 3}
library(pheatmap)
pheatmap(matSim_MLP,
         cluster_rows = F,
         color = heatmapPalette,
         legend = T)
```

```{r}
source("/projects/abeauchamp/Projects/MouseHumanMapping/Functions/ProcessingTools.R")

#Normalize mouse data
dfExprMouse_scaled <- dfExprMouse %>% 
  select(-contains("Region")) %>% 
  as.matrix() %>% 
  scaler(axis = "rows") %>% 
  scaler(scale = FALSE, axis = "columns") %>% 
  as_tibble() %>% 
  bind_cols(dfLabelsMouse)

#Normalize human data
dfExprHuman_scaled <- dfExprHuman %>% 
  select(-contains("Region")) %>% 
  as.matrix() %>% 
  scaler(axis = "rows") %>% 
  scaler(scale = FALSE, axis = "columns") %>% 
  as_tibble() %>% 
  bind_cols(dfLabelsHuman)

genes <- colnames(dfExprMouse_scaled)[!str_detect(colnames(dfExprMouse_scaled), "Region|VoxelID")]
```


```{r}
matHumanExpr <- dfExprHuman_scaled %>% 
  filter(Region16 %in% structsHuman_Cx_16,
             !(Region88 %in% c("claustrum", "dentate gyrus", "CA1 field", "CA2 field", "CA3 field", "CA4 field", "subiculum"))) %>%
  select(all_of(genes),
         Region = Region166) %>% 
  group_by(Region) %>% 
  summarise_all(mean) %>% 
  ungroup() %>% 
  column_to_rownames("Region") %>% 
  as.matrix() %>% 
  t()

matMouseExpr <- dfExprMouse_scaled %>% 
  filter(Region11 == "Isocortex") %>% 
  select(all_of(genes),
         Region = Region67) %>% 
  group_by(Region) %>% 
  summarise_all(mean) %>% 
  ungroup() %>% 
  column_to_rownames("Region") %>% 
  as.matrix() %>% 
  t()

matSim_AllGenes <- buildSimilarityMatrix(x1 = matHumanExpr,
                                         x2 = matMouseExpr,
                                         method = "correlation") %>% 
  t()

matSim_AllGenes <- matSim_AllGenes[match(mouseOrder, rownames(matSim_AllGenes)),] 


```


```{r}
dfSim_AllGenes <- matSim_AllGenes %>% 
  as_tibble(rownames = "MouseRegion") %>% 
  pivot_longer(cols = -MouseRegion, names_to = "HumanRegion", values_to = "Correlation")

dfSim_AllGenes_MaxSim <- dfSim_AllGenes %>% 
  group_by(HumanRegion) %>% 
  filter(Correlation == max(Correlation)) %>% 
  ungroup() %>% 
  select(HumanRegion, MouseRegion, Correlation) %>% 
  arrange(desc(Correlation))
```

```{r fig.height = 3, fig.width = 4}
dfSim_AllGenes_MaxSim %>% 
  mutate(HumanRegion = factor(HumanRegion, levels = HumanRegion[order(Correlation)]),
         CortexType = case_when(HumanRegion %in% structsHuman_PFC_agranular ~ "Agranular",
                                HumanRegion %in% structsHuman_PFC_granular ~ "Granular",
                                !(HumanRegion %in% structsHuman_PFC) ~ "Other")) %>% 
  ggplot(aes(x = HumanRegion, y = Correlation, col = CortexType)) + 
  geom_segment(aes(xend = HumanRegion,
                   yend = 0)) + 
  geom_point() + 
  coord_flip() + 
  scale_y_continuous(expand = expansion(mult = c(0, 0.1))) + 
  scale_color_manual(labels = c("Agranular", "Granular", "Not annotated"),
                     values = c(RColorBrewer::brewer.pal(3, name = "Set1")[1:2], "grey70")) + 
  theme_bw()
```

```{r fig.height = 3, fig.width = 3}
temp <- dfSim_AllGenes %>% 
  group_by(HumanRegion) %>% 
  mutate(IsMaximal = ifelse(Correlation == max(Correlation), TRUE, FALSE)) %>% 
  ungroup() %>% 
  filter(HumanRegion %in% structsHuman_PFC) %>% 
  mutate(MouseRegion = factor(MouseRegion, levels = rev(mouseOrder)),
         HumanRegion = factor(HumanRegion, levels = structsHuman_PFC),
         IsMaximalLabel = ifelse(IsMaximal == TRUE, "*", ""))

ggplot(temp, aes(x = HumanRegion, y = MouseRegion, fill = Correlation)) + 
  geom_tile(col = "grey50") + 
  geom_text(aes(label = IsMaximalLabel),
            size = 6, nudge_y = -0.3) + 
  scale_x_discrete(expand = expansion(mult = 0)) + 
  scale_y_discrete(expand = expansion(mult = 0)) + 
  scale_fill_viridis_c(option = "magma", begin = 0.35) + 
  labs(x = "Human region",
       y = "Mouse region") + 
  theme_bw() + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5))
```

```{r fig.width = 6, fig.height = 3}
p <- pheatmap(matSim_AllGenes,
         color = heatmapPalette,
         cutree_rows = 4,
         cutree_cols = 4)
```

```{r fig.height = 3, fig.width = 8}
humanOrder <- p$tree_col$labels[p$tree_col$order]
mouseOrder <- p$tree_row$labels[p$tree_row$order]

temp <- dfSim_AllGenes %>% 
  group_by(HumanRegion) %>% 
  mutate(IsMaximal = ifelse(Correlation == max(Correlation), TRUE, FALSE)) %>% 
  ungroup() %>% 
  mutate(MouseRegion = factor(MouseRegion, levels = rev(mouseOrder)),
         HumanRegion = factor(HumanRegion, levels = humanOrder),
         IsMaximalLabel = ifelse(IsMaximal == TRUE, "*", ""))

ggplot(temp, aes(x = HumanRegion, y = MouseRegion, fill = Correlation)) + 
  geom_tile(col = "grey50") + 
  geom_text(aes(label = IsMaximalLabel),
            size = 6, nudge_y = -0.3) + 
  scale_x_discrete(expand = expansion(mult = 0)) + 
  scale_y_discrete(expand = expansion(mult = 0)) + 
  scale_fill_viridis_c(option = "magma", begin = 0.35) + 
  labs(x = "Human region",
       y = "Mouse region") + 
  theme_bw() + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5))
```
