#!/bin/bash

markdown_files=(*_AMBA_legend.Rmd)
markdown_files+=(*_figure[12].Rmd)
#markdown_files=(*_figure*.Rmd)

for file in ${markdown_files[@]};
do
	Rscript convert_markdowns.R --infile $file
	r_file="${file/".Rmd"/".R"}"
	echo "Executing ${r_file} "
	Rscript $r_file 
	rm $r_file
done

