#!/bin/bash

markdown_files=(*_AMBA_legend.Rmd)
markdown_files+=(*_figure*.Rmd)

for file in ${markdown_files[@]};
do
	Rscript convert_markdown.R --infile $file
	
	r_file="${file/".Rmd"/".R"}"
	
	echo "Executing ${r_file} "
	Rscript $r_file 
	
	rm $r_file
	
	if [ -f Rplots.pdf ]; 
	then
		rm Rplots.pdf
	fi
done

