---
title: "Untitled"
author: "Antoine Beauchamp"
date: '2021-11-09'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries}
#Libraries
suppressPackageStartupMessages(library(tidyverse))
library(grid)
library(gridExtra)
library(pheatmap)
library(ggplotify)
library(ggnewscale)
library(RMINC)
library(MRIcrotome)
library(data.tree)
library(RColorBrewer)
```

```{r functions}
#Functions
source("/projects/abeauchamp/Functions/TreeTools.R")
source("/projects/abeauchamp/Functions/mincBuildArray.R")
source("/projects/abeauchamp/Projects/MouseHumanMapping/Functions/ProcessingTools.R")
source("/projects/abeauchamp/Projects/MouseHumanMapping/Functions/buildSimilarityMatrix.R")
```

```{r import}
#Set path
pathHome <- "/projects/abeauchamp/Projects/MouseHumanMapping/Paper_Descriptive/"

#Import data
dfExprMouse <- suppressMessages(read_csv(str_c(pathHome, "Data/", "MouseExpressionMatrix_Voxel_coronal_maskcoronal_imputed_labelled.csv")))
dfExprHuman <- suppressMessages(read_csv(str_c(pathHome, "Data/", "HumanExpressionMatrix_Samples_labelled.csv")))

#Load mouse/human labels (Objects: listLabelsMouseReordered, listLabelsHumanReordered)
load(str_c(pathHome, "Data/", "TreeLabelsReordered.RData"))

#Import MICe data tree
load(str_c("/projects/abeauchamp/Projects/MouseHumanMapping/AllenMouseBrainAtlas/Data/MouseExpressionTree_DSURQE.RData"))
treeMouse <- Clone(treeMouseExpr)
rm(treeMouseExpr)

#Remove white matter and ventricles
pruneAnatTree(treeMouse, 
              nodes = c("fiber tracts", "ventricular systems"),
              method = "AtNode")

#Import AHBA data tree
load("/projects/abeauchamp/Projects/MouseHumanMapping/AllenHumanBrainAtlas/Data/HumanExpressionTree_Samples.RData")
treeHuman <- Clone(treeHumanExpr)
rm(treeHumanExpr)

#Fix human colour names (need to start with #)
treeHuman$Do(function(node){
  node$color_hex_triplet <- str_c("#", node$color_hex_triplet)
})

#Remove white matter and ventricles
pruneAnatTree(treeHuman,
              nodes = c("white matter", "sulci & spaces"),
              method = "AtNode")

#Import DSURQE labels and template
dsurqeLabels <- mincGetVolume("/projects/abeauchamp/Atlases/DSURQE/DSURQE_40micron_labels.mnc")
dsurqeAnat <- mincGetVolume("/projects/abeauchamp/Atlases/DSURQE/DSURQE_40micron_average.mnc")
dsurqeMask <- mincGetVolume("/projects/abeauchamp/Atlases/DSURQE/DSURQE_40micron_mask.mnc")
```

```{r normalization}
#Extract labels from data frames
dfLabelsMouse <- dfExprMouse %>% select(contains("Region"))
dfLabelsHuman <- dfExprHuman %>% select(contains("Region"))

#Normalize mouse data
dfExprMouse_scaled <- dfExprMouse %>% 
  select(-contains("Region")) %>% 
  as.matrix() %>% 
  scaler(axis = "rows") %>% 
  scaler(scale = FALSE, axis = "columns") %>% 
  as_tibble() %>% 
  bind_cols(dfLabelsMouse)

#Normalize human data
dfExprHuman_scaled <- dfExprHuman %>% 
  select(-contains("Region")) %>% 
  as.matrix() %>% 
  scaler(axis = "rows") %>% 
  scaler(scale = FALSE, axis = "columns") %>% 
  as_tibble() %>% 
  bind_cols(dfLabelsHuman)

#Extract genes list from mouse data (same as human)
genes <- colnames(dfExprMouse_scaled)[!str_detect(colnames(dfExprMouse_scaled), "Region")]

rm(dfExprMouse, dfExprHuman)
```

```{r}
#Compute average gene expression for 67 mouse brain regions
matExprMouse_scaled <- dfExprMouse_scaled %>% 
  select(Region = Region67,
         genes) %>% 
  group_by(Region) %>% 
  summarise_all(mean) %>% 
  ungroup() %>% 
  column_to_rownames("Region") %>% 
  as.matrix() %>% 
  t()

#Compute average gene expression for 88 human brain regions
matExprHuman_scaled <- dfExprHuman_scaled %>% 
  select(Region = Region88,
         genes) %>% 
  group_by(Region) %>% 
  summarise_all(mean) %>% 
  ungroup() %>% 
  column_to_rownames("Region") %>% 
  as.matrix() %>% 
  t()

#Compute human-mouse similarity matrix in gene space
matSim_H88M67_AllGenes <- buildSimilarityMatrix(x1 = matExprHuman_scaled, 
                                                x2 = matExprMouse_scaled)
```

```{r}
#Set human seed regions
seeds <- c("precentral gyrus",
           "cuneus",
           "crus I")

#Generate a mouse tree with 67 leaf nodes
treeMouse_67 <- Clone(treeMouse)
pruneAnatTree(treeMouse_67,
              nodes = listLabelsMouseReordered$Region67_reordered,
              method = "BelowNode")

#Create a mouse atlas with 67 regions
atlasMouse_67 <- hanatToAtlas(treeMouse_67, mincArray(dsurqeLabels))
dfAtlasMouse_67 <- hanatToAtlasDefs(treeMouse_67)

#Extract seed similarities
dfSeedSim_AllGenes <- matSim_H88M67_AllGenes %>% 
  t() %>% 
  as_tibble(rownames = "Target") %>% 
  select(Target, seeds)

#Convert seed similarities to MINC array
listSeedSim_AllGenes <- map(.x = select(dfSeedSim_AllGenes, -Target),
                            .f = mincBuildArray,
                            labels = atlasMouse_67,
                            defs = dfAtlasMouse_67,
                            values.names = dfSeedSim_AllGenes$Target)

#Apply mask to the background anatomy
dsurqeAnat[dsurqeMask == 0] <- 0
```

```{r}
anatomy <- mincArray(dsurqeAnat)
mask <- mincArray(dsurqeMask)
overlay <- mincArray(listSeedSim_AllGenes[['precentral gyrus']])

anatomyLow <- 700
anatomyHigh <- 1400

nrow <- 4
ncol <- 5

sliceBegin <- 100
sliceEnd <- 200
slices <- floor(seq(sliceBegin, sliceEnd, length.out = nRow*nCol))
slices <- c(100, 200)

plane <- "coronal"

tibbleSliceSeries <- function(anatomy, mask, overlay, nrow, ncol, slices, begin = NULL, end = NULL, plane = "coronal"){
  
  dims <- dim(anatomy)
  anatomy[mask == 0] <- NA
  overlay[mask == 0] <- NA
  # anatomy[anatomy >= anatomyHigh] <- anatomyHigh
  # anatomy[anatomy <= anatomyLow] <- anatomyLow  
  
  if(plane == 'sagittal'){
    x <- dims[2]:1
    y <- 1:dims[3]
  } else if (plane == 'coronal') {
    x <- dims[1]:1
    y <- 1:dims[3]
  } else if (plane == 'axial') {
    x <- dims[1]:1
    y <- 1:dims[2]
  } else {
    stop()
  }
  
  df_slices <- expand_grid(slice = slices,
                           x = x,
                           y = y,
                           anatomy = NA,
                           overlay = NA)
  
  for(i in 1:length(slices)){
    
    if (plane == "sagittal"){
      slice_anatomy <- anatomy[slices[i],,]
      slice_overlay <- overlay[slices[i],,]
    } else if (plane == "coronal") {
      slice_anatomy <- anatomy[,slices[i],]
      slice_overlay <- overlay[,slices[i],]
    } else if (plane == "axial") {
      slice_anatomy <- anatomy[,,slices[i]]
      slice_overlay <- overlay[,,slices[i]]
    } else {
      stop()
    }
    colnames(slice_anatomy) <- 1:ncol(slice_anatomy)
    rownames(slice_anatomy) <- nrow(slice_anatomy):1
    
    slice_anatomy_vals <- slice_anatomy %>% 
      as_tibble(rownames = "x") %>% 
      pivot_longer(-x, names_to = "y", values_to = "values") %>% 
      pull(values)
    
    df_slices[df_slices$slice == slices[i], "anatomy"] <- slice_anatomy_vals
    
    colnames(slice_overlay) <- 1:ncol(slice_overlay)
    rownames(slice_overlay) <- nrow(slice_overlay):1
    
    slice_overlay_vals <- slice_overlay %>% 
      as_tibble(rownames = "x") %>% 
      pivot_longer(-x, names_to = "y", values_to = "values") %>% 
      pull(values)
    
    df_slices[df_slices$slice == slices[i], "overlay"] <- slice_overlay_vals
    
  }
  
  return(df_slices)
  
}

dfSlices <- tibbleSliceSeries(anatomy = mincArray(dsurqeAnat),
                              mask = mincArray(dsurqeMask),
                              overlay =  mincArray(listSeedSim_AllGenes[['precentral gyrus']]),
                              nrow = 8, ncol = 1, slices = seq(70, 330, length.out = 8), plane = "coronal")

library(ggnewscale)
```


```{r fig.width = 8}
limit <- max(abs(dfSlices$overlay), na.rm = T)*c(-1, 1)

ind <- dfSlices$overlay <= 0.2 & dfSlices$overlay >= -0.2 & !is.na(dfSlices$overlay)
dfSlices[ind, 'overlay'] <- NA


ggplot(dfSlices, aes(x = x, y = y)) + 
  coord_fixed() + 
  facet_wrap(facets = vars(slice),
             nrow = 2,
             ncol = 4) + 
  geom_tile(aes(fill = anatomy)) + 
  scale_fill_gradient(low = gray.colors(255)[1],
                      high = gray.colors(255)[255],
                      na.value = 'transparent',
                      guide = F) + 
  new_scale_fill() + 
  geom_tile(aes(fill = overlay)) + 
  scale_fill_gradientn(colours = colorRampPalette(rev(brewer.pal(n = 9, name = "RdBu")))(255),
                       na.value = 'transparent',
                       limits = limit) + 
  # scale_fill_gradient(na.value = 'transparent') +
    theme_minimal() +
    theme(strip.text = element_blank(),
          axis.title = element_blank(),
          axis.text = element_blank(),
          axis.ticks = element_blank(),
          panel.border = element_rect(color = "black",
                                      fill = NA),
          plot.background = element_rect(color = "black"),
          panel.spacing = unit(0.25, 'lines'))
```


```{r}
treeMouse_11 <- Clone(treeMouse)
pruneAnatTree(treeMouse_11,
              nodes = listLabelsMouseReordered$Region11_reordered,
              method = "BelowNode")
atlasMouse_11 <- hanatToAtlas(treeMouse_11, mincArray(dsurqeLabels))
dfAtlasMouse_11 <- hanatToAtlasDefs(treeMouse_11)

dsurqeAnat_3d <- mincArray(dsurqeAnat)
dsurqeMask_3d <- mincArray(dsurqeMask)

dsurqeAnat_3d[dsurqeMask_3d == 0] <- NA

anatLow <-  700
anatHigh <- 1400
dsurqeAnat_3d[dsurqeAnat_3d >= anatHigh] <- anatHigh
dsurqeAnat_3d[dsurqeAnat_3d <= anatLow] <- anatLow
dims <- dim(dsurqeAnat_3d)

slice <- 100
sliceSelectionAnat <- dsurqeAnat_3d[1:dims[1], 1:dims[2], slice]
colnames(sliceSelectionAnat) <- 1:ncol(sliceSelectionAnat)
rownames(sliceSelectionAnat) <- nrow(sliceSelectionAnat):1

dfSliceSelectionAnat <- sliceSelectionAnat %>% 
  as_tibble(rownames = "x") %>% 
  pivot_longer(-x, names_to = "y", values_to = "Intensity") %>% 
  mutate_all(.funs = as.numeric)

atlasMouse_11_3d <- mincArray(atlasMouse_11)
atlasMouse_11_3d[dsurqeMask_3d == 0] <- NA
atlasMouse_11_3d[atlasMouse_11_3d == 0] <- NA
sliceSelectionLabels <- atlasMouse_11_3d[1:dims[1], 1:dims[2], slice]
colnames(sliceSelectionLabels) <- 1:ncol(sliceSelectionLabels)
rownames(sliceSelectionLabels) <- nrow(sliceSelectionLabels):1

dfSliceSelectionLabels <- sliceSelectionLabels %>% 
  as_tibble(rownames = "x") %>% 
  pivot_longer(-x, names_to = "y", values_to = "Label") %>% 
  mutate_all(.funs = as.numeric) 

dfSliceSelection <- inner_join(dfSliceSelectionAnat,
                               dfSliceSelectionLabels,
                               by = c("x", "y"))

dfMouseColours <- treeMouse_11$Get("color_hex_triplet", filterFun = isLeaf) %>%
  enframe(name = "Structure",
          value = "Colour") %>% 
  inner_join(dfAtlasMouse_11,
             by = "Structure") %>% 
  semi_join(dfSliceSelection,
            by = "Label") %>% 
  arrange(Label)

dfSliceSelection <- dfSliceSelection %>% 
  filter(y <= 400) %>% 
  mutate(Label = factor(Label))

asp <- max(dfSliceSelection$x)/max(dfSliceSelection$y)

sliceAMBALegend <- ggplot(dfSliceSelection, aes(x = x, y = y)) + 
  geom_tile(aes(fill = Intensity),
            alpha = 0.5) + 
  scale_fill_gradient(low = gray.colors(255)[1],
                      high = gray.colors(255)[255],
                      na.value = 'transparent',
                      guide = F) + 
  new_scale_fill() + 
  geom_tile(aes(fill = Label)) + 
  scale_fill_manual(na.value = 'transparent',
                      values = dfMouseColours$Colour,
                    guide = F) +
  coord_fixed() +
  theme_void() +
  # theme_minimal() +
  theme(plot.margin = margin(t = 0, r = 0, b = 0, l = 0))
sliceAMBALegend_grob <- ggplotGrob(sliceAMBALegend) %>% grid.force()
sliceAMBALegend_panel_grob <- getGrob(sliceAMBALegend_grob, "panel.7-5-7-5")

rm(treeMouse_11,
   atlasMouse_11,
   dfAtlasMouse_11,
   dsurqeAnat_3d,
   dsurqeMask_3d,
   slice,
   sliceSelectionAnat,
   atlasMouse_11_3d,
   sliceSelectionLabels,
   dfSliceSelectionAnat,
   dfSliceSelectionLabels,
   dfSliceSelection,
   dfMouseColours)
```

