#!/bin/bash

source activate_venv

# Download AHBA data from the web
echo "Downloading AHBA data..."
python3 download_AHBA.py

# Build sample expression matrix 
echo "Building human gene-by-sample expression matrix..."
Rscript build_sample_matrix.R --version 1 --verbose true

# Build sample tree
echo "Building human neuroanatomical tree..."
Rscript build_human_tree.R

