---
title: "Transcriptomic similarity in the mouse and human brain"
subtitle: "Allen Mouse Brain Atlas legend slice"
author: "Antoine Beauchamp"
date: 'January 19th, 2022'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      include = FALSE,
                      cache.lazy = FALSE)
```

```{r libraries}
suppressPackageStartupMessages(library(tidyverse))
library(data.tree)
library(RMINC)
library(ggnewscale)
library(grid)
library(gridExtra)
```

```{r functions}
source("/projects/abeauchamp/Functions/TreeTools.R")
```

```{r import}
#Set path
pathHome <- "/projects/abeauchamp/Projects/MouseHumanMapping/Paper_Descriptive/"

#Load mouse/human labels (Objects: listLabelsMouseReordered, listLabelsHumanReordered)
load(str_c(pathHome, "Data/", "TreeLabelsReordered.RData"))

#Import MICe data tree
load(str_c("/projects/abeauchamp/Projects/MouseHumanMapping/AllenMouseBrainAtlas/Data/MouseExpressionTree_DSURQE.RData"))
treeMouse <- Clone(treeMouseExpr)
rm(treeMouseExpr)

#Remove white matter and ventricles
pruneAnatTree(treeMouse, 
              nodes = c("fiber tracts", "ventricular systems"),
              method = "AtNode")

#Import DSURQE labels and template
dsurqeLabels <- mincGetVolume("/projects/abeauchamp/Atlases/DSURQE/DSURQE_40micron_labels.mnc")
dsurqeAnat <- mincGetVolume("/projects/abeauchamp/Atlases/DSURQE/DSURQE_40micron_average.mnc")
dsurqeMask <- mincGetVolume("/projects/abeauchamp/Atlases/DSURQE/DSURQE_40micron_mask.mnc")
```

```{r slice-atlas}
#Prune the AMBA tree down to 11 coarse labels
treeMouse_11 <- Clone(treeMouse)
pruneAnatTree(treeMouse_11,
              nodes = listLabelsMouseReordered$Region11_reordered,
              method = "BelowNode")

#Extract the atlas labels and definitions for the 11-label atlas
atlasMouse_11 <- hanatToAtlas(treeMouse_11, mincArray(dsurqeLabels))
dfAtlasMouse_11 <- hanatToAtlasDefs(treeMouse_11)

#Get the AMBA colours for the 11 regions
dfAtlasMouse_11 <- treeMouse_11$Get("color_hex_triplet", filterFun = isLeaf) %>%
  enframe(name = "Structure",
          value = "Colour") %>% 
  inner_join(dfAtlasMouse_11,
             by = "Structure")
```

```{r slice-background}
#Convert the DSURQE template and mask to a 3D array
dsurqeAnat_3d <- mincArray(dsurqeAnat)
dsurqeMask_3d <- mincArray(dsurqeMask)

#Masked values are set to NA
dsurqeAnat_3d[dsurqeMask_3d == 0] <- NA

#Specify lower and upper intensity thresholds for the template
anatLow <-  700
anatHigh <- 1400

#Clamp the template intensity based on thresholds
dsurqeAnat_3d[dsurqeAnat_3d >= anatHigh] <- anatHigh
dsurqeAnat_3d[dsurqeAnat_3d <= anatLow] <- anatLow

#Extract the dimensions of the volume
dims <- dim(dsurqeAnat_3d)

#Extract the slice that we'll use for our legend. Transverse so 3rd array dimension
slice <- 100
sliceSelectionAnat <- dsurqeAnat_3d[1:dims[1], 1:dims[2], slice]

#Include x and y voxel coordinates as column/row names
colnames(sliceSelectionAnat) <- 1:ncol(sliceSelectionAnat)
rownames(sliceSelectionAnat) <- nrow(sliceSelectionAnat):1

#Convert the slice image to a long form data frame
dfSliceSelectionAnat <- sliceSelectionAnat %>% 
  as_tibble(rownames = "x") %>% 
  pivot_longer(-x, names_to = "y", values_to = "Intensity") %>% 
  mutate_all(.funs = as.numeric)
```

```{r slice-labels}
#Convert the 11-label atlas to a 3D volume
atlasMouse_11_3d <- mincArray(atlasMouse_11)

#Assign NA values to voxels outside the mask
atlasMouse_11_3d[dsurqeMask_3d == 0] <- NA

#Assign NA values to voxels that have a 0 label
atlasMouse_11_3d[atlasMouse_11_3d == 0] <- NA

#Extract the transverse slice (same as above)
sliceSelectionLabels <- atlasMouse_11_3d[1:dims[1], 1:dims[2], slice]

#Store voxel coordinates in row and column names
colnames(sliceSelectionLabels) <- 1:ncol(sliceSelectionLabels)
rownames(sliceSelectionLabels) <- nrow(sliceSelectionLabels):1

#Convert the label image to a long form data frame
dfSliceSelectionLabels <- sliceSelectionLabels %>% 
  as_tibble(rownames = "x") %>% 
  pivot_longer(-x, names_to = "y", values_to = "Label") %>% 
  mutate_all(.funs = as.numeric)
```

```{r make-slice-legend}
#Combine the background and label data frames into one
dfSliceSelection <- inner_join(dfSliceSelectionAnat,
                               dfSliceSelectionLabels,
                               by = c("x", "y"))

#Creatte a data frame containing the AMBA colours for the labels in the slice
dfMouseColours <- dfAtlasMouse_11 %>% 
  semi_join(dfSliceSelection,
            by = "Label") %>% 
  arrange(Label)

#Crop the y axis and convert the atlas labels to factor
dfSliceSelection <- dfSliceSelection %>% 
  filter(y <= 400) %>% 
  mutate(Label = factor(Label))

#Extract the aspect ratio of the slice
sliceAMBA_asp <- max(dfSliceSelection$x)/max(dfSliceSelection$y)

#Create the base plot for the slice legend
sliceAMBALegend <- ggplot(dfSliceSelection, aes(x = x, y = y)) + 
  geom_tile(aes(fill = Intensity),
            alpha = 0.5) + 
  scale_fill_gradient(low = gray.colors(255)[1],
                      high = gray.colors(255)[255],
                      na.value = 'transparent',
                      guide = "none") + 
  new_scale_fill() + 
  geom_tile(aes(fill = Label)) + 
  scale_fill_manual(na.value = 'transparent',
                      values = dfMouseColours$Colour,
                    guide = "none") +
  coord_fixed() +
  theme_void() +
  theme(plot.margin = margin(t = 0, r = 0, b = 0, l = 0))

#Extract the panel grob for the slice (we don't need any other grobs)
sliceAMBALegend_grob <- ggplotGrob(sliceAMBALegend) %>% 
  grid.force() %>% 
  getGrob("panel.7-5-7-5")
# sliceAMBALegend_panel_grob <- getGrob(sliceAMBALegend_grob, "panel.7-5-7-5")
```

```{r fig-dims}
fig_height <- 4
fig_width <- fig_height*sliceAMBA_asp
print(c(fig_width, fig_height))
```

```{r slice-grob, fig.width = 3.15, fig.height = 4}
grid.newpage()
grid.draw(sliceAMBALegend_grob)
```

```{r write}
#Save the grob for the slice
fileout <- str_c(pathHome, "Draft/", "Version5/", "AMBALegendSlice.RData")
save(sliceAMBALegend_grob,
     sliceAMBA_asp,
     file = fileout)
```
