#!/bin/bash

source activate_venv

# Download AHBA data from the web
echo "Downloading AMBA coronal in-situ hybridization data set..."
#python3 download_AMBA.py --dataset coronal --outdir data/expression/ --metadata AMBA_metadata_coronal.csv --parallel true --nproc 12

echo "Downloading AMBA sagittal in-situ hybridization data set..."
#python3 download_AMBA.py --dataset sagittal --outdir data/expression/ --metadata AMBA_metadata_sagittal.csv --parallel true --nproc 12

# Build voxel expression matrix 
echo "Building mouse gene-by-voxel expression matrix using coronal data with coronal mask..."
python3 build_voxel_matrix.py --datadir data/expression/ --outdir data/ --dataset coronal --mask coronal --log2 true --groupexp true --threshold 0.2 --impute true --parallel true --nproc 4 

echo "Building mouse gene-by-voxel expression matrix using coronal data with sagittal mask..."
python3 build_voxel_matrix.py --datadir data/expression/ --outdir data/ --dataset coronal --mask sagittal --log2 true --groupexp false --threshold 0.2 --impute true --parallel true --nproc 4 

echo "Building mouse gene-by-voxel expression matrix using sagittal data with sagittal mask..."
python3 build_voxel_matrix.py --datadir data/expression/ --outdir data/ --dataset sagittal --mask sagittal --log2 true --groupexp true --threshold 0.2 --impute true --parallel true --nproc 4 

# Build data tree
