---
title: "Mouse Human Mapping Paper 1"
subtitle: "Figure 6"
author: "Antoine Beauchamp"
date: "November 12th, 2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      include = FALSE,
                      cache.lazy = FALSE)
```

# Main

```{r libraries}
#Libraries
suppressPackageStartupMessages(library(tidyverse))
library(grid)
library(gridExtra)
library(pheatmap)
library(ggplotify)
library(ggnewscale)
library(RMINC)
library(MRIcrotome)
library(data.tree)
library(RColorBrewer)
```

```{r functions}
#Functions
source("/projects/abeauchamp/Functions/TreeTools.R")
source("/projects/abeauchamp/Projects/MouseHumanMapping/Functions/buildSimilarityMatrix.R")
source("/projects/abeauchamp/Projects/MouseHumanMapping/Functions/ProcessingTools.R")
```

```{r import-general}
#Path
pathHome <- "/projects/abeauchamp/Projects/MouseHumanMapping/Paper_Descriptive/"

#Import mouse voxelwise gene expression matrix
dfExprMouse <- suppressMessages(read_csv(str_c(pathHome, "Data/", "MouseExpressionMatrix_Voxel_coronal_maskcoronal_imputed_labelled_scaled.csv"))) 
dfExprHuman <- suppressMessages(read_csv(str_c(pathHome, "Data/", "HumanExpressionMatrix_Samples_labelled_scaled.csv"))) 

#Extract gene names
genes <- colnames(dfExprMouse)[!str_detect(colnames(dfExprMouse), "Region")]

#Load mouse/human labels (Objects: listLabelsMouseReordered, listLabelsHumanReordered)
load(str_c(pathHome, "Data/", "TreeLabelsReordered.RData"))

#Import MICe data tree
load(str_c("/projects/abeauchamp/Projects/MouseHumanMapping/AllenMouseBrainAtlas/Data/MouseExpressionTree_DSURQE.RData"))
treeMouse <- Clone(treeMouseExpr)
rm(treeMouseExpr)

#Remove white matter and ventricles
pruneAnatTree(treeMouse,
              nodes = c("fiber tracts", "ventricular systems"),
              method = "AtNode")

#Import AHBA data tree
load("/projects/abeauchamp/Projects/MouseHumanMapping/AllenHumanBrainAtlas/Data/HumanExpressionTree_Samples.RData")
treeHuman <- Clone(treeHumanExpr)
rm(treeHumanExpr)

#Fix human colour names (need to start with #)
treeHuman$Do(function(node){
  node$color_hex_triplet <- str_c("#", node$color_hex_triplet)
})

#Remove white matter and ventricles
pruneAnatTree(treeHuman,
              nodes = c("white matter", "sulci & spaces"),
              method = "AtNode")

#Import DSURQE images in AMBA space
dsurqeLabels_200um <- mincGetVolume("/projects/abeauchamp/Projects/MouseHumanMapping/AllenMouseBrainAtlas/Data/MRI/DSURQE_Allen_labels.mnc")
dsurqeMask_200um <- mincGetVolume("/projects/abeauchamp/Projects/MouseHumanMapping/AllenMouseBrainAtlas/Data/MRI/coronal_200um_coverage_bin0.8.mnc")
dsurqeAverage_200um <- mincGetVolume("/projects/abeauchamp/Projects/MouseHumanMapping/AllenMouseBrainAtlas/Data/MRI/DSURQE_Allen_average.mnc")

#Create a correspondence between voxels in the image space and in the expression matrices

#Indices for the mask and for grey matter ROIs
indMask <- dsurqeMask_200um == 1
indGM <- dsurqeLabels_200um %in% treeMouse$`Basic cell groups and regions`$label
indVoxels <- indMask & indGM
rm(indGM, indMask)

#Create an empty array and assign IDs to non-null voxels
emptyArray <- numeric(length(dsurqeLabels_200um))
names(emptyArray) <- character(length(emptyArray))
voxelNames <- str_c("V", 1:sum(indVoxels))
names(emptyArray)[indVoxels] <- voxelNames
rm(indVoxels)
```

```{r normalization}
#Extract labels from data frames
#Extract mouse voxel labels
dfLabelsMouse <- dfExprMouse %>% 
  select(contains("Region")) %>% 
  mutate(VoxelID = str_c("V", 1:nrow(.)))

#Extract mouse samples labels
dfLabelsHuman <- dfExprHuman %>% 
  select(contains("Region")) %>% 
  mutate(SampleID = str_c("S", 1:nrow(.)))

#Normalize mouse data
dfExprMouse_scaled <- dfExprMouse %>% 
  select(-contains("Region")) %>% 
  as.matrix() %>% 
  scaler(axis = "rows") %>% 
  scaler(scale = FALSE, axis = "columns") %>% 
  as_tibble() %>% 
  bind_cols(dfLabelsMouse)

#Normalize human data
dfExprHuman_scaled <- dfExprHuman %>% 
  select(-contains("Region")) %>% 
  as.matrix() %>% 
  scaler(axis = "rows") %>% 
  scaler(scale = FALSE, axis = "columns") %>% 
  as_tibble() %>% 
  bind_cols(dfLabelsHuman)

#Extract genes list from mouse data (same as human)
genes <- colnames(dfExprMouse_scaled)[!str_detect(colnames(dfExprMouse_scaled), "Region|VoxelID")]

rm(dfExprMouse, dfExprHuman)
```



```{r}
striatumHuman <- c("caudate nucleus", 
                   "putamen",
                   "nucleus accumbens")

matExprHuman_Striatum <- dfExprHuman_scaled %>%
  select(Region88, genes) %>% 
  filter(Region88 %in% striatumHuman) %>% 
  group_by(Region88) %>% 
  summarise_all(.funs = mean) %>% 
  ungroup() %>% 
  column_to_rownames("Region88") %>% 
  as.matrix() %>% 
  t()

matExprMouse_CP <- dfExprMouse_scaled %>% 
  filter(Region67 == "Caudoputamen") %>% 
  select(VoxelID, genes) %>% 
  column_to_rownames("VoxelID") %>% 
  as.matrix() %>% 
  t() 

matSim_CP <- buildSimilarityMatrix(x1 = matExprHuman_Striatum, 
                                   x2 = matExprMouse_CP)

matSim_CP_t <- t(matSim_CP)
```

```{r}
listArrayHumanTargets <- vector(mode = "list", length = ncol(matSim_CP_t))
names(listArrayHumanTargets) <- colnames(matSim_CP_t)
listArrayHumanTargets <- map(listArrayHumanTargets, function(x){return(emptyArray)})
for(j in 1:ncol(matSim_CP_t)){
  indVoxelMatch <- match(rownames(matSim_CP_t), names(emptyArray))
  listArrayHumanTargets[[j]][indVoxelMatch] <- matSim_CP_t[,j]
  attributes(listArrayHumanTargets[[j]]) <- attributes(dsurqeLabels_200um)
}
```

```{r fig.width = 10, fig.height = 3}
overlayRange <- c(0.3, 0.4)
sliceSeries(nrow = 1, ncol = 8, begin = 34, end = 47) %>% 
  anatomy(mincArray(dsurqeAverage_200um), low = 700, high = 1400) %>% 
  overlay(mincArray(listArrayHumanTargets[["caudate nucleus"]]), symmetric = T, low = overlayRange[1], high = overlayRange[2]) %>% 
  addtitle("Caudate") %>% 
  sliceSeries() %>% anatomy() %>% 
  overlay(mincArray(listArrayHumanTargets[["putamen"]]), symmetric = T, low = overlayRange[1], high = overlayRange[2]) %>% 
  addtitle("Putamen") %>% 
  sliceSeries() %>% anatomy() %>% 
  overlay(mincArray(listArrayHumanTargets[["nucleus accumbens"]]), symmetric = T, low = overlayRange[1], high = overlayRange[2]) %>% 
  addtitle("Accumbens") %>% 
  legend("Correlation") %>% 
  draw(layout = "row")
```

```{r}
vdiff <- matSim_CP_t[,"caudate nucleus"] - matSim_CP_t[,"putamen"]
arrayDiff <- emptyArray
indVoxelMatch <- match(names(vdiff), names(emptyArray)) 
arrayDiff[indVoxelMatch] <- vdiff
attributes(arrayDiff) <- attributes(dsurqeLabels_200um)

sliceSeries(nrow = 4, ncol = 4, begin = 34, end = 47) %>% 
  anatomy(mincArray(dsurqeAverage_200um), low = 700, high = 1400) %>% 
  overlay(mincArray(arrayDiff), symmetric = T, low = 0, high = 0.02) %>% 
  legend("Correlation difference") %>% 
  addtitle("[Caudate correlation] - [putamen correlation]") %>% 
  draw()
```

```{r}
j <- sample(1:ncol(matExprMouse_CP), size = 1)
dfExampleModel <- tibble(HumanCaudate = matExprHuman_Striatum[,"caudate nucleus"],
                         HumanPutamen = matExprHuman_Striatum[,"putamen"],
                         MouseCPVoxel = matExprMouse_CP[,j])
# mod_example_caudate <- lm(HumanCaudate ~ MouseCPVoxel, data = dfExampleModel)
mod_example_caudate <- lm(MouseCPVoxel ~ HumanCaudate, data = dfExampleModel)
intercept_caudate <- summary(mod_example_caudate)$coef[1, "Estimate"]
beta_caudate <- summary(mod_example_caudate)$coef[2, "Estimate"]

dfExampleModel <- dfExampleModel %>% 
  mutate(CaudateResiduals = residuals(mod_example_caudate))

mod_example_putamen <- lm(CaudateResiduals ~ HumanPutamen, data = dfExampleModel)
intercept_putamen <- summary(mod_example_putamen)$coef[1, "Estimate"]
beta_putamen <- summary(mod_example_putamen)$coef[2, "Estimate"]
```

```{r}
summary(mod_example_caudate)$adj.r.squared
summary(mod_example_putamen)$adj.r.squared
```

```{r}
1 - sigma(mod_example_caudate)/var(matExprMouse_CP[,j])

```
```{r}
summary(mod_example_caudate)
```


```{r fig.width = 10, fig.height = 5}
pcaudate <- ggplot(dfExampleModel, aes(x = HumanCaudate, y = MouseCPVoxel)) + 
  geom_point(size = 0.75) + 
  geom_abline(intercept = intercept_caudate, 
              slope = beta_caudate,
              linetype = "dashed",
              col = "red") + 
  coord_cartesian(xlim = c(-5.5, 5.5),
                  ylim = c(-6, 6)) +
  labs(y = "Mouse caudoputamen sample voxel expression",
       x = "Human caudate average expression") + 
  theme_bw()

pputamen <- ggplot(dfExampleModel, aes(x = HumanPutamen, y = CaudateResiduals)) + 
  geom_point(size = 0.75) + 
  geom_abline(intercept = intercept_putamen, 
              slope = beta_putamen,
              linetype = "dashed",
              col = "red") + 
  coord_cartesian(xlim = c(-5.5, 5.5),
                  ylim = c(-6, 6)) +
  labs(y = "Caudate model residuals",
       x = "Human putamen average expression") + 
  theme_bw()

library(patchwork)
pcaudate + pputamen
```

```{r}
dfParams <- tibble(VoxelID = colnames(matExprMouse_CP),
                   beta = 0,
                   sigma_beta = 0,
                   tval = 0,
                   pval = 0,
                   rsquared_caudate = 0,
                   rsquared_putamen = 0)

for(j in 1:ncol(matExprMouse_CP)){
  mod_caudate <- lm(matExprMouse_CP[,j] ~ matExprHuman_Striatum[,"caudate nucleus"])
  mod_putamen <- lm(residuals(mod_caudate) ~ matExprHuman_Striatum[,"putamen"])
  
  dfParams[j, "beta"] <- summary(mod_putamen)$coef[2, "Estimate"]
  dfParams[j, "sigma_beta"] <- summary(mod_putamen)$coef[2, "Std. Error"]
  dfParams[j, "tval"] <- summary(mod_putamen)$coef[2, "t value"]
  dfParams[j, "pval"] <- summary(mod_putamen)$coef[2, "Pr(>|t|)"]
  dfParams[j, "rsquared_caudate"] <- summary(mod_caudate)$r.squared
  dfParams[j, "rsquared_putamen"] <- summary(mod_putamen)$r.squared
}
```

```{r fig.width = 10, fig.height = 4}
ylims <- c(0, 0.06)
pvoxel_tval <- ggplot(dfParams, aes(x = tval, y = ..count../nrow(dfParams))) + 
  geom_histogram(bins = 40,
                 fill = "grey70",
                 col = "black") + 
  coord_cartesian(xlim = c(-2, 2),
                  ylim = ylims) + 
  scale_x_continuous(breaks = seq(-2, 2, 0.5)) + 
  labs(x = "t-value",
       y = "Fraction of caudoputamen voxels") + 
  theme_bw()

pvoxel_pval <- ggplot(dfParams, aes(x = pval, y = ..count../nrow(dfParams))) + 
  geom_histogram(bins = 40,
                 fill = "grey70",
                 col = "black") + 
  coord_cartesian(xlim = c(0, 1),
                  ylim = ylims) + 
  scale_x_continuous(breaks = seq(0, 1, by = 0.1)) + 
  labs(x = "p-value") + 
  theme_bw() + 
  theme(axis.title.y = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank())

(pvoxel_tval | pvoxel_pval) 
```


```{r}
dfParams_R2 <- dfParams %>% 
  select(contains("rsquared")) %>% 
  pivot_longer(cols = everything(), names_to = "Model", values_to = "R2") %>% 
  mutate(Model = ifelse(Model == "rsquared_caudate", "Voxel ~ Caudate", "Residuals ~ Putamen"),
         Model = factor(Model, levels = c("Voxel ~ Caudate", "Residuals ~ Putamen")))

ggplot(dfParams_R2, aes(x = R2, y = ..count../nrow(dfParams))) + 
  geom_histogram(bins = 50,
                 fill = "grey70",
                 col = "black") + 
  facet_wrap(~Model, ncol = 2, scales = "free_x") + 
  labs(x = "Coefficient of determination",
       y = "Fraction of caudoputamen voxels",
       title = "Variation in mouse CP expression explained by caudate and putamen") + 
  theme_bw()
```


```{r}
indVoxelMatch <- match(dfParams$VoxelID, names(emptyArray))

cp_tvals <- emptyArray
cp_pvals <- emptyArray

cp_tvals[indVoxelMatch] <- dfParams$tval
cp_pvals[indVoxelMatch] <- 1-dfParams$pval

attributes(cp_tvals) <- attributes(dsurqeLabels_200um)
attributes(cp_pvals) <- attributes(dsurqeLabels_200um)

sliceSeries(nrow = 4, ncol = 2, begin = 34, end = 47) %>% 
  anatomy(mincArray(dsurqeAverage_200um), low = 700, high = 1400) %>% 
  overlay(mincArray(cp_tvals), symmetric = T, low = 0.1, high = 1.5) %>% 
  legend("t-value") %>% 
  sliceSeries() %>% anatomy() %>% 
  overlay(mincArray(cp_pvals), symmetric = F, low = 0.1, high = 0.95) %>% 
  legend("1 - p-value") %>% 
  draw()
```

```{r}
dfParams <- tibble(VoxelID = colnames(matExprMouse_CP),
                   beta = 0,
                   sigma_beta = 0,
                   tval = 0,
                   pval = 0,
                   rsquared_caudate = 0,
                   rsquared_putamen = 0)

for(j in 1:ncol(matExprMouse_CP)){
  mod_putamen <- lm(matExprMouse_CP[,j] ~ matExprHuman_Striatum[,"putamen"])
  mod_caudate <- lm(residuals(mod_putamen) ~ matExprHuman_Striatum[,"caudate nucleus"])
  
  dfParams[j, "beta"] <- summary(mod_caudate)$coef[2, "Estimate"]
  dfParams[j, "sigma_beta"] <- summary(mod_caudate)$coef[2, "Std. Error"]
  dfParams[j, "tval"] <- summary(mod_caudate)$coef[2, "t value"]
  dfParams[j, "pval"] <- summary(mod_caudate)$coef[2, "Pr(>|t|)"]
  dfParams[j, "rsquared_caudate"] <- summary(mod_caudate)$r.squared
  dfParams[j, "rsquared_putamen"] <- summary(mod_putamen)$r.squared
}
```

```{r}
dfParams_R2 <- dfParams %>% 
  select(contains("rsquared")) %>% 
  pivot_longer(cols = everything(), names_to = "Model", values_to = "R2") %>% 
  mutate(Model = ifelse(Model == "rsquared_putamen", "Voxel ~ Putamen", "Residuals ~ Caudate"),
         Model = factor(Model, levels = c("Voxel ~ Putamen", "Residuals ~ Caudate")))

ggplot(dfParams_R2, aes(x = R2, y = ..count../nrow(dfParams))) + 
  geom_histogram(bins = 50,
                 fill = "grey70",
                 col = "black") + 
  facet_wrap(~Model, ncol = 2, scales = "free_x") + 
  labs(x = "Coefficient of determination",
       y = "Fraction of caudoputamen voxels",
       title = "Variation in mouse CP expression explained by caudate and putamen") + 
  theme_bw()
```

```{r}
indVoxelMatch <- match(dfParams$VoxelID, names(emptyArray))

cp_tvals <- emptyArray
cp_pvals <- emptyArray

cp_tvals[indVoxelMatch] <- dfParams$tval
cp_pvals[indVoxelMatch] <- 1-dfParams$pval

attributes(cp_tvals) <- attributes(dsurqeLabels_200um)
attributes(cp_pvals) <- attributes(dsurqeLabels_200um)

sliceSeries(nrow = 4, ncol = 2, begin = 34, end = 47) %>% 
  anatomy(mincArray(dsurqeAverage_200um), low = 700, high = 1400) %>% 
  overlay(mincArray(cp_tvals), symmetric = T, low = 0.1, high = 1.5) %>% 
  legend("t-value") %>% 
  sliceSeries() %>% anatomy() %>% 
  overlay(mincArray(cp_pvals), symmetric = F, low = 0.1, high = 0.95) %>% 
  legend("1 - p-value") %>% 
  draw()
```


