---
title: "Untitled"
author: "Antoine Beauchamp"
date: "November 16, 2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries}
#Libraries
suppressPackageStartupMessages(library(tidyverse))
library(grid)
library(gridExtra)
library(pheatmap)
library(ggplotify)
library(ggnewscale)
library(RMINC)
library(MRIcrotome)
library(data.tree)
library(RColorBrewer)
```

```{r functions}
#Functions
source("../../../functions/tree_tools.R")
source("../../../functions/mincBuildArray.R")
source("../../../functions/processing_tools.R")
source("../../../functions/buildSimilarityMatrix.R")
```

```{r import}
#Import data
dfExprMouse <- suppressMessages(read_csv("../../../data/MouseExpressionMatrix_voxel_coronal_maskcoronal_log2_grouped_imputed_labelled.csv"))
dfExprHuman <- suppressMessages(read_csv("../../../data/HumanExpressionMatrix_Samples_pipeline_v1_labelled.csv"))

#Load mouse/human labels (Objects: listLabelsMouseReordered, listLabelsHumanReordered)
load("../../../data/TreeLabelsReordered.RData")

#Import MICe data tree
load("../../../AMBA/data/MouseExpressionTree_DSURQE.RData")
treeMouse <- Clone(treeMouseExpr)
rm(treeMouseExpr)

#Remove white matter and ventricles
pruneAnatTree(treeMouse, 
              nodes = c("fiber tracts", "ventricular systems"),
              method = "AtNode")

#Import AHBA data tree
load("../../../AHBA/data/HumanExpressionTree.RData")
treeHuman <- Clone(treeHumanExpr)
rm(treeHumanExpr)

#Fix human colour names (need to start with #)
treeHuman$Do(function(node){
  node$color_hex_triplet <- str_c("#", node$color_hex_triplet)
})

#Remove white matter and ventricles
pruneAnatTree(treeHuman,
              nodes = c("white matter", "sulci & spaces"),
              method = "AtNode")

#Import DSURQE labels and template
dsurqeLabels <- mincGetVolume("../../../AMBA/data/imaging/DSURQE_40micron_labels.mnc")
dsurqeAnat <- mincGetVolume("../../../AMBA/data/imaging/DSURQE_40micron_average.mnc")
dsurqeMask <- mincGetVolume("../../../AMBA/data/imaging/DSURQE_40micron_mask.mnc")
```

```{r}
treeMouse_67 <- Clone(treeMouse)
pruneAnatTree(treeMouse_67,
              nodes = listLabelsMouseReordered$Region67_reordered,
              method = "BelowNode")
```

```{r}
library(ape)
as.phylo.Node(FindNode(treeMouse_67, "Cerebellar nuclei"))
```

```{r}
node <- Clone(treeMouse_67)

function (node, heightAttribute = DefaultPlotHeight, ...) 
{
    deparse <- function(x) {
        name <- str_replace_all(x$name, " ", "_")
        name <- str_replace_all(name, ",", "")
        if (!isRoot(x) && length(heightAttribute) > 0) {
            edge <- GetAttribute(x$parent, heightAttribute, ...) - 
                GetAttribute(x, heightAttribute, ...)
            me <- paste0(name, ":", edge)
        }
        else {
            me <- name
        }
        return(me)
    }
    
    Newick <- function(x) {
        if (x$isLeaf) {
            return(deparse(x))
        }
        chNewick <- sapply(x$children, Newick)
        chNewickStr <- paste(chNewick, collapse = ",")
        res <- paste0("(", chNewickStr, ")", deparse(x))
    }
    res <- Newick(node)
    res <- paste0(res, ";")
    return(res)
}

Newick <- function(x) {
        if (x$isLeaf) {
            return(deparse(x))
        }
        chNewick <- sapply(x$children, Newick)
        chNewickStr <- paste(chNewick, collapse = ",")
        res <- paste0("(", chNewickStr, ")", deparse(x))
}
```

```{r}
res <- Newick(node)
```


```{r}
data(acme)
as.phylo.Node(acme)
```

```{r}
treeTemp <- Clone(treeMouse_67)
treeTemp <- FindNode(treeTemp, "Basic cell groups and regions")
treeTemp$Do(function(node){
  if("Vermal regions" %in% node$path[-length(node$path)]){
    node$name <- node$name %>% str_remove_all("\\(|\\)") %>% str_replace_all(" ", "_")
  }
  
  if(node$name == "Ammon's horn"){
    node$name <- "Ammon horn"
  }
})
treePhylo <- as.phylo(treeTemp)
```


```{r}
library(tidytree)
library(ggtree)
```

```{r}
x <- as_tibble(treePhylo)

d <- tibble(label = listLabelsMouseReordered$Region67_reordered,
            val = rnorm(67))

y <- left_join(x, d, by = "label")


treeTidy <- as.treedata(y)

as_tibble(treeTidy)
```

Looks like we can plot directly using a phylo object. Don't have to convert to tidy tree

```{r}
# ggplot(treeTidy, aes(x, y)) + geom_tree()
ggtree(treePhylo, layout = "circular")
```

```{r}
nwk <- system.file("extdata", "sample.nwk", package = "treeio")
tree <- read.tree(nwk)
circ <- ggtree(tree, layout = "circular") + geom_tiplab(offset = 0)
circ
```
```{r}
df <- data.frame(first = c("a", "b", "a", "c", "d", "d", "a", "b", "e", "e", "f", "c", "f"))
rownames(df) <- tree$tip.label

gheatmap(circ, df, offset = 1, width = 0.2, colnames_angle = 95, colnames_offset_y = 0.25) + 
  scale_fill_viridis_d(option = "D", name = "discrete\nvalue")
```

```{r}
circ <- ggtree(treePhylo, layout = "circular")
df <- tibble(label = treePhylo$tip.label,
             val = rnorm(n = 67)) %>% 
  column_to_rownames("label")

# gheatmap(circ, df, colnames = F, offset = 2)
circ + geom_tiplab()
```

https://yulab-smu.top/treedata-book/chapter1.html#get-treedata-data
https://yulab-smu.top/treedata-book/chapter7.html#attach-operator
https://4va.github.io/biodatasci/r-ggtree.html
https://github.com/YuLab-SMU/ggtree/issues/367

