---
title: "Mouse Human Mapping Paper 1"
subtitle: "Figure 5"
author: "Antoine Beauchamp"
date: 'November 3rd, 2021'
output: html_document
---

```{r libraries}
#Libraries
suppressPackageStartupMessages(library(tidyverse))
library(grid)
library(gridExtra)
library(pheatmap)
library(ggplotify)
library(ggnewscale)
library(RMINC)
library(MRIcrotome)
library(data.tree)
library(RColorBrewer)
```

```{r functions}
#Functions
source("/projects/abeauchamp/Functions/TreeTools.R")
source("/projects/abeauchamp/Functions/mincBuildArray.R")
source("/projects/abeauchamp/Projects/MouseHumanMapping/Functions/ProcessingTools.R")
source("/projects/abeauchamp/Projects/MouseHumanMapping/Functions/buildSimilarityMatrix.R")
```

```{r import}
#Set path
pathHome <- "/projects/abeauchamp/Projects/MouseHumanMapping/Paper_Descriptive/"

#Import data
dfExprMouse <- suppressMessages(read_csv(str_c(pathHome, "Data/", "MouseExpressionMatrix_Voxel_coronal_maskcoronal_imputed_labelled.csv")))
dfExprHuman <- suppressMessages(read_csv(str_c(pathHome, "Data/", "HumanExpressionMatrix_Samples_labelled.csv")))

#Load mouse/human labels (Objects: listLabelsMouseReordered, listLabelsHumanReordered)
load(str_c(pathHome, "Data/", "TreeLabelsReordered.RData"))

#Import MICe data tree
load(str_c("/projects/abeauchamp/Projects/MouseHumanMapping/AllenMouseBrainAtlas/Data/MouseExpressionTree_DSURQE.RData"))
treeMouse <- Clone(treeMouseExpr)
rm(treeMouseExpr)

#Remove white matter and ventricles
pruneAnatTree(treeMouse, 
              nodes = c("fiber tracts", "ventricular systems"),
              method = "AtNode")

#Import AHBA data tree
load("/projects/abeauchamp/Projects/MouseHumanMapping/AllenHumanBrainAtlas/Data/HumanExpressionTree_Samples.RData")
treeHuman <- Clone(treeHumanExpr)
rm(treeHumanExpr)

#Fix human colour names (need to start with #)
treeHuman$Do(function(node){
  node$color_hex_triplet <- str_c("#", node$color_hex_triplet)
})

#Remove white matter and ventricles
pruneAnatTree(treeHuman,
              nodes = c("white matter", "sulci & spaces"),
              method = "AtNode")

#Import DSURQE labels and template
dsurqeLabels <- mincGetVolume("/projects/abeauchamp/Atlases/DSURQE/DSURQE_40micron_labels.mnc")
dsurqeAnat <- mincGetVolume("/projects/abeauchamp/Atlases/DSURQE/DSURQE_40micron_average.mnc")
dsurqeMask <- mincGetVolume("/projects/abeauchamp/Atlases/DSURQE/DSURQE_40micron_mask.mnc")
```

```{r normalization}
#Extract labels from data frames
dfLabelsMouse <- dfExprMouse %>% select(contains("Region"))
dfLabelsHuman <- dfExprHuman %>% select(contains("Region"))

#Normalize mouse data
dfExprMouse_scaled <- dfExprMouse %>% 
  select(-contains("Region")) %>% 
  as.matrix() %>% 
  scaler(axis = "rows") %>% 
  scaler(scale = FALSE, axis = "columns") %>% 
  as_tibble() %>% 
  bind_cols(dfLabelsMouse)

#Normalize human data
dfExprHuman_scaled <- dfExprHuman %>% 
  select(-contains("Region")) %>% 
  as.matrix() %>% 
  scaler(axis = "rows") %>% 
  scaler(scale = FALSE, axis = "columns") %>% 
  as_tibble() %>% 
  bind_cols(dfLabelsHuman)

#Extract genes list from mouse data (same as human)
genes <- colnames(dfExprMouse_scaled)[!str_detect(colnames(dfExprMouse_scaled), "Region")]

rm(dfExprMouse, dfExprHuman)
```

```{r results2-fig2-processing}
#Path to MLP files
pathMLP <- str_c(pathHome, "Data/MultilayerPerceptronOutcomes/")

#Files containing latent space representations
filesMLP_Mouse <- list.files(pathMLP, pattern = "MouseTx", full.names = T)
filesMLP_Human <- list.files(pathMLP, pattern = "HumanTx", full.names = T)

#Import the mouse latent space data
listMouseLatentSpace <- map(filesMLP_Mouse,
                            function(x){
                              suppressMessages(read_csv(x)) %>% 
                                column_to_rownames("Region") %>% 
                                as.matrix() %>% 
                                t()
                            })

#Import the human latent space data
listHumanLatentSpace <- map(filesMLP_Human,
                            function(x){
                              suppressMessages(read_csv(x)) %>% 
                                column_to_rownames("Region") %>% 
                                as.matrix() %>% 
                                t()
                            })

#Compute the latent space similarity matrices
listSimLatentSpace <- map2(listHumanLatentSpace, listMouseLatentSpace,
                           function(x1, x2){
                             m <- buildSimilarityMatrix(x1 = x1, x2 = x2)
                             m <- m[,match(listLabelsMouseReordered$Region67_reordered, colnames(m))]
                             m <- m[match(listLabelsHumanReordered$Region88_reordered, rownames(m)),]
                           })
names(listSimLatentSpace) <- str_c("MLP_v", 1:length(listSimLatentSpace))
rm(listMouseLatentSpace, listHumanLatentSpace)
```

```{r results3-fig5-processing}
#' Compute scaled similarity profiles for every column in a similarity matrix
#'
#' @param similarity A similarity matrix
#' @param scale A logical value indicating whether to scale the similarity profiles
#'
#' @return A tibble containing the scaled similarity profiles
computeSimilarityProfiles <- function(similarity, scale = FALSE){
  
  profiles <- tibble()
  for(seed in colnames(similarity)){
    temp <- similarity[, seed] %>% 
      enframe(name = "Target",
              value = "Similarity") 
      
      if(scale){
        temp <- temp %>% 
          mutate(Similarity = (Similarity - min(Similarity))/(max(Similarity) - min(Similarity)))
      }
    
    temp <- temp %>% 
      mutate(TargetRank = as.numeric(factor(Target, levels = Target[order(Similarity, decreasing = TRUE)])),
             Seed = seed)
    profiles <- bind_rows(profiles, temp)
  }
  return(profiles)
}


#Compute similarity profiles in MLP latent spaces
dfSimilarityProfiles <- map_dfr(.x = listSimLatentSpace,
                                .f = computeSimilarityProfiles,
                                .id = "Data")

#Generate a mouse tree with 67 leaf nodes
treeMouse_67 <- Clone(treeMouse)
pruneAnatTree(treeMouse_67,
              nodes = listLabelsMouseReordered$Region67_reordered,
              method = "BelowNode")

#Extracts mouse regions in isocortex
treeMouse_Cx <- FindNode(treeMouse_67, "Isocortex")
structsMouse_Cx <- treeMouse_Cx$Get("name", filterFun = isLeaf)

#Filter similarity profiles for isocortical regions
dfSimilarityProfiles_Cx <- dfSimilarityProfiles %>% 
  filter(Seed %in% structsMouse_Cx)

#Define sensory isocortical regions
structsMouse_Cx_sensory <- c("Primary auditory area",
                             "Dorsal auditory area",
                             "Ventral auditory area",
                             "Primary motor area",
                             "Secondary motor area",
                             "Primary somatosensory area",
                             "Supplemental somatosensory area",
                             "Visual areas")

#Define association isocortical regions
structsMouse_Cx_association <- structsMouse_Cx[!(structsMouse_Cx %in% structsMouse_Cx_sensory)]
```

```{r results3-fig5-panelA-regional}
#Identify maximal similarity values for every seed and data set
dfSimilarityProfiles_Cx_MaxSim <- dfSimilarityProfiles_Cx %>%
  group_by(Data, Seed) %>% 
  filter(Similarity == max(Similarity)) %>% 
  ungroup()

#Compute maximal similarity summary statistics for each isocortical region
dfSimilarityProfiles_Cx_MaxSim_Summary <- dfSimilarityProfiles_Cx_MaxSim %>% 
  group_by(Seed) %>% 
  summarise(SimilarityMean = mean(Similarity),
            SimilaritySdLower = SimilarityMean - 2*sd(Similarity),
            SimilaritySdUpper = SimilarityMean + 2*sd(Similarity)) %>% 
  ungroup() %>% 
  mutate(Seed = factor(Seed, levels = Seed[order(SimilarityMean)]),
         CortexType = ifelse(Seed %in% structsMouse_Cx_sensory, "Sensorimotor", "Association"))

fig5_regionaldist <- ggplot(dfSimilarityProfiles_Cx_MaxSim_Summary, 
       aes(x = Seed, 
           y = SimilarityMean,
           ymin = SimilaritySdLower,
           ymax = SimilaritySdUpper,
           col = CortexType)) + 
  geom_pointrange() + 
  coord_flip() +
  scale_colour_manual(values = c("#B27700", "#00325C")) +
  labs(x = "Mouse isocortical regions",
       y = "Maximal correlation",
       col = "Type of cortex") + 
  theme_bw() + 
  theme(legend.title = element_blank(),
        legend.position = "bottom",
        legend.direction = "horizontal",
        plot.margin = margin(l = 0, r = 0, b = 0, t = 0, unit = 'inch'))
fig5_regionaldist_grob <- ggplotGrob(fig5_regionaldist) %>% grid.force()

#Extract legend from plot
fig5_regionaldist_legend_grob <- getGrob(fig5_regionaldist_grob, "guides.3-3-3-3")
fig5_regionaldist <- fig5_regionaldist + 
  theme(legend.position = "none")
fig5_regionaldist_grob <- ggplotGrob(fig5_regionaldist) %>% grid.force()
```

```{r results3-fig5-panelB-cortextype}
#Compute mean maximal similarity per cortex type and data set
dfSimilarityProfiles_Cx_MaxSim_Compare <- dfSimilarityProfiles_Cx_MaxSim %>% 
  mutate(CortexType = ifelse(Seed %in% structsMouse_Cx_sensory, "Sensorimotor", "Association")) %>% 
  group_by(Data, CortexType) %>% 
  summarise(SimilarityMean = mean(Similarity)) %>%
  ungroup()

#Set seed for jittering
set.seed(123)

#Plot
fig5_cortexdist <- ggplot(dfSimilarityProfiles_Cx_MaxSim_Compare,
       aes(x = CortexType, y = SimilarityMean)) + 
  geom_jitter(width = 0.2,
              col = "grey80",
              size = 1) + 
  geom_boxplot(outlier.shape = NA,
               alpha = 0.3) + 
  labs(x = "Type of cortex",
       y = "Average maximal correlation") + 
  theme_bw() + 
  theme(plot.margin = margin(l = 0, r = 0, b = 0, t = 0, unit = 'inch'))
fig5_cortexdist_grob <- ggplotGrob(fig5_cortexdist) %>% grid.force()
```

```{r results3-fig5-grob}
#Figure 5 title grob
fig5_title <- textGrob("Conservation of mouse cortical sensorimotor and association areas",
                       x =  0.65)

#Generate figure 5 grob
# fig5_grob <- arrangeGrob(fig5_regionaldist_grob, #1
#                          fig5_regionaldist_legend_grob, #2
#                          fig5_regionaldist_title_grob, #3
#                          fig5_cortexdist_grob, #4
#                          fig5_cortexdist_title_grob, #5
#                          layout_matrix = rbind(c(NA,  3, 3, NA,  5, NA),
#                                                c(NA,  1, 1, NA,  4, NA),
#                                                c(NA, NA, 2, NA, NA, NA)),
#                          widths = unit(c(0.2, 2.238, 2.238, 0.25, 2.875, 0.2), 'inch'),
#                          heights = unit(c(0.25, 4.2, 0.25), 'inch'))
fig5_grob <- arrangeGrob(fig5_regionaldist_grob, #1
                         fig5_regionaldist_legend_grob, #2
                         fig5_cortexdist_grob, #3
                         fig5_title, #4
                         layout_matrix = rbind(c(NA,  4,  4,  4,  4, NA),
                                               c(NA,  1,  1, NA,  3, NA),
                                               c(NA, NA,  2, NA, NA, NA),
                                               c(NA, NA, NA, NA, NA, NA)),
                         widths = unit(c(0.2, 2.238, 2.238, 0.25, 2.875, 0.2), 'inch'),
                         heights = unit(c(0.4, 4.2, 0.25, 0.2), 'inch'))
```

```{r results3-fig5-interactive, include=TRUE, echo=FALSE, fig.width=8, fig.height=5.2}
grid.newpage()
grid.draw(fig5_grob)
grid.rect(gp = gpar(fill = NA))
grid.text(c("A.", "B."),
          x = unit(c(0.29, 5.02), 'inch'),
          y = unit(rep(0.88, 2), 'npc'),
          gp = gpar(fontsize = 14, fontface = "bold"))
```

```{r results3-fig5-write}
fileout <- str_c(pathHome, "Draft/", "Version4/", "Figure5.RData")
save(fig5_grob,
     file = fileout)
```

# Supplementary

```{r}
#Compute similarity profiles in MLP latent spaces
dfSimilarityProfilesScaled <- map_dfr(.x = listSimLatentSpace,
                                      .f = computeSimilarityProfiles,
                                      .id = "Data",
                                      scale = TRUE)

dfRankThresholds_Cx <- dfSimilarityProfilesScaled %>% 
  filter(Similarity >= 0.75) %>% 
  group_by(Data, Seed) %>% 
  filter(Similarity == min(Similarity)) %>% 
  ungroup() %>% 
  filter(Seed %in% structsMouse_Cx)

dfRankThresholds_Cx
```


```{r}
dfRankThresholds_Cx_Summary <- dfRankThresholds_Cx %>% 
  group_by(Seed) %>% 
  summarise(RankMean = mean(TargetRank),
            RankSdLower = RankMean - 2*sd(TargetRank),
            RankSdUpper = RankMean + 2*sd(TargetRank)) %>% 
  ungroup() %>% 
  mutate(Seed = factor(Seed, levels = Seed[order(RankMean, decreasing = T)]),
         CortexType = ifelse(Seed %in% structsMouse_Cx_sensory, "Sensorimotor", "Association"))

ggplot(dfRankThresholds_Cx_Summary,
       aes(y = Seed,
           x = RankMean,
           xmin = RankSdLower,
           xmax = RankSdUpper,
           col = CortexType)) + 
  geom_pointrange() + 
  labs(x = "Rank at s = 0.75",
       y = "Mouse isocortical region",
       col = "Cortex type") + 
  theme_bw()
```

```{r}
temp1 <- dfSimilarityProfilesScaled %>% 
  filter(Seed == "Infralimbic area")

temp2 <- dfSimilarityProfilesScaled %>% 
  filter(Seed == "Primary somatosensory area")

ggplot(temp1, aes(x = TargetRank, y = Similarity, group = Data)) + 
  geom_line(size = 0.04,
            col = "#B27700") + 
  geom_line(data = temp2,
            size = 0.04,
            col = "#00325C") + 
  annotate(geom = "text",
           label = c("Infralimbic area", "Primary somatosensory area"),
           x = c(12,60),
           y = c(0.25, 0.8),
           col = c("#B27700", "#00325C")) + 
  labs(x = "Human rank",
       y = "Scaled similarity") + 
  theme_bw()
```

```{r}
temp <- dfSimilarityProfilesScaled_Cx %>% 
  group_by(Seed, TargetRank) %>% 
  summarise(MeanSimilarity = mean(Similarity)) %>% 
  ungroup() %>% 
  mutate(CortexType = ifelse(Seed %in% structsMouse_Cx_sensory, "Sensorimotor", "Association"))

ggplot(temp, aes(x = TargetRank, y = MeanSimilarity, col = CortexType, group = Seed)) +
  geom_line() + 
  theme_bw()
```

```{r}
dfLabelsHuman$Region16 %>% unique

dfLabelsHuman %>% 
  filter(Region16 %in% c("frontal lobe", "insula", "temporal lobe", "parietal lobe", "occipital lobe")) %>% 
  pull(Region88) %>% 
  unique() %>% 
  length()
```

```{r}
dfParams <- expand_grid(Data = unique(dfSimilarityProfilesScaled_Cx$Data),
                        Seed = unique(dfSimilarityProfilesScaled_Cx$Seed),
                        beta = 0) %>% 
  arrange(Seed)

beta0 <- 1
for(i in 1:nrow(dfParams)){
  
  if(i %% 50 == 0){print(i)}
  
  temp <- dfSimilarityProfilesScaled_Cx %>% 
    filter(TargetRank < 36,
           Seed == dfParams[[i,"Seed"]],
           Data == dfParams[[i, "Data"]]) 
  
  mod <- lm(I(Similarity - beta0) ~ 0 + TargetRank, data = temp)
  dfParams[[i, "beta"]] <- coef(mod)['TargetRank']
}

temp <- dfParams %>% 
  mutate(beta_abs = abs(beta)) %>% 
  group_by(Seed) %>% 
  summarise(ParamMean = mean(beta_abs),
            ParamSdLower = ParamMean - sd(beta_abs),
            ParamSdUpper = ParamMean + sd(beta_abs)) %>% 
  ungroup() %>% 
  mutate(CortexType = ifelse(Seed %in% structsMouse_Cx_sensory, "Sensorimotor", "Association"),
         Seed = factor(Seed, levels = Seed[order(ParamMean)]))

ggplot(temp, aes(y = Seed, x = ParamMean, xmin = ParamSdLower, xmax = ParamSdUpper, col = CortexType)) + 
  geom_pointrange() +
  
  theme_bw()
```

```{r}
dfIDs <- dfSimilarityProfilesScaled_Cx %>% 
  select(Data, Seed) %>% 
  distinct() %>% 
  mutate(ID = 1:nrow(.))

temp <- dfSimilarityProfilesScaled_Cx %>% 
  mutate(CortexType = ifelse(Seed %in% structsMouse_Cx_sensory, "Sensorimotor", "Association")) %>% 
  inner_join(dfIDs, by = c("Data", "Seed"))

temp <- dfSimilarityProfilesScaled_Cx %>% 
  mutate(CortexType = ifelse(Seed %in% structsMouse_Cx_sensory, "Sensorimotor", "Association")) %>% 
  group_by(CortexType, TargetRank) %>% 
  summarise(MeanSimilarity = mean(Similarity),
            Lower = MeanSimilarity - sd(Similarity),
            Upper = MeanSimilarity + sd(Similarity)) %>% 
  ungroup()


ggplot(temp, aes(x = TargetRank, fill = CortexType)) + 
  geom_ribbon(aes(y = MeanSimilarity,
                  ymin = Lower,
                  ymax = Upper),
              alpha = 0.2) +
  geom_line(aes(y = MeanSimilarity, col = CortexType)) + 
  scale_colour_manual(values = RColorBrewer::brewer.pal(n = 9, name = "Set1")[c(2, 5)]) + 
  scale_fill_manual(values = RColorBrewer::brewer.pal(n = 9, name = "Set1")[c(2, 5)]) + 
  labs(x = "Human rank",
       y = "Averaged scaled similarity",
       fill = "Cortex type",
       col = "Cortex type",
       caption = "Summaries computed over latent spaces and ROIs") + 
  theme_bw()
```




```{r results3-fig5-panelA-regional}
#Identify maximal similarity values for every seed and data set
dfSimilarityProfiles_Cx_MaxSim <- dfSimilarityProfiles_Cx %>%
  group_by(Data, Seed) %>% 
  filter(Similarity == max(Similarity)) %>% 
  ungroup()

#Compute maximal similarity summary statistics for each isocortical region
dfSimilarityProfiles_Cx_MaxSim_Summary <- dfSimilarityProfiles_Cx_MaxSim %>% 
  group_by(Seed) %>% 
  summarise(SimilarityMean = mean(Similarity),
            SimilaritySdLower = SimilarityMean - 2*sd(Similarity),
            SimilaritySdUpper = SimilarityMean + 2*sd(Similarity)) %>% 
  ungroup() %>% 
  mutate(Seed = factor(Seed, levels = Seed[order(SimilarityMean)]),
         CortexType = ifelse(Seed %in% structsMouse_Cx_sensory, "Sensorimotor", "Association"))

fig5_regionaldist <- ggplot(dfSimilarityProfiles_Cx_MaxSim_Summary, 
       aes(x = Seed, 
           y = SimilarityMean,
           ymin = SimilaritySdLower,
           ymax = SimilaritySdUpper,
           col = CortexType)) + 
  geom_pointrange() + 
  coord_flip() +
  scale_colour_manual(values = c("#B27700", "#00325C")) +
  labs(x = "Mouse isocortical regions",
       y = "Maximal correlation",
       col = "Type of cortex") + 
  theme_bw() + 
  theme(legend.title = element_blank(),
        legend.position = "bottom",
        legend.direction = "horizontal",
        plot.margin = margin(l = 0, r = 0, b = 0, t = 0, unit = 'inch'))
fig5_regionaldist_grob <- ggplotGrob(fig5_regionaldist) %>% grid.force()

#Extract legend from plot
fig5_regionaldist_legend_grob <- getGrob(fig5_regionaldist_grob, "guides.3-3-3-3")
fig5_regionaldist <- fig5_regionaldist + 
  theme(legend.position = "none")
fig5_regionaldist_grob <- ggplotGrob(fig5_regionaldist) %>% grid.force()
```
